// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: planningCenter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from planningCenter.proto</summary>
  public static partial class PlanningCenterReflection {

    #region Descriptor
    /// <summary>File descriptor for planningCenter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanningCenterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwbGFubmluZ0NlbnRlci5wcm90bxIHcnYuZGF0YRoQYmFzaWNUeXBlcy5w",
            "cm90bxoPdGltZXN0YW1wLnByb3RvGhJwcmVzZW50YXRpb24ucHJvdG8i5QoK",
            "ElBsYW5uaW5nQ2VudGVyUGxhbhITCgtwbGFuX2lkX251bRgBIAEoDRIVCg1w",
            "YXJlbnRfaWRfbnVtGAIgASgNEhQKDHNlcmllc190aXRsZRgDIAEoCRISCgpw",
            "bGFuX3RpdGxlGAQgASgJEhEKCWRhdGVfbGlzdBgFIAEoCRIoCgxjcmVhdGVk",
            "X2RhdGUYBiABKAsyEi5ydi5kYXRhLlRpbWVzdGFtcBInCgt1cGRhdGVfZGF0",
            "ZRgHIAEoCzISLnJ2LmRhdGEuVGltZXN0YW1wEjIKFmxhc3RfdXBkYXRlX2No",
            "ZWNrX2RhdGUYCCABKAsyEi5ydi5kYXRhLlRpbWVzdGFtcBITCgtwbGFuX2lk",
            "X3N0chgJIAEoCRIVCg1wYXJlbnRfaWRfc3RyGAogASgJGrIICghQbGFuSXRl",
            "bRJECglpdGVtX3R5cGUYASABKA4yMS5ydi5kYXRhLlBsYW5uaW5nQ2VudGVy",
            "UGxhbi5QbGFuSXRlbS5QbGFuSXRlbVR5cGUSEgoKcGNvX2lkX251bRgCIAEo",
            "DRIWCg5zZXJ2aWNlX2lkX251bRgDIAEoDRIVCg1wYXJlbnRfaWRfbnVtGAQg",
            "ASgNEgwKBG5hbWUYBSABKAkSRAoLYXR0YWNobWVudHMYBiADKAsyLy5ydi5k",
            "YXRhLlBsYW5uaW5nQ2VudGVyUGxhbi5QbGFuSXRlbS5BdHRhY2htZW50EicK",
            "C3VwZGF0ZV9kYXRlGAcgASgLMhIucnYuZGF0YS5UaW1lc3RhbXASQgoLbGlu",
            "a2VkX3NvbmcYCCABKAsyLS5ydi5kYXRhLlBsYW5uaW5nQ2VudGVyUGxhbi5Q",
            "bGFuSXRlbS5Tb25nSXRlbRISCgpwY29faWRfc3RyGAkgASgJEhYKDnNlcnZp",
            "Y2VfaWRfc3RyGAogASgJEhUKDXBhcmVudF9pZF9zdHIYCyABKAka6QEKCkF0",
            "dGFjaG1lbnQSDAoEbmFtZRgBIAEoCRIZCgN1cmwYAiABKAsyDC5ydi5kYXRh",
            "LlVSTBIoCgxjcmVhdGVkX2RhdGUYAyABKAsyEi5ydi5kYXRhLlRpbWVzdGFt",
            "cBIhCgtsaW5rZWRfcGF0aBgEIAEoCzIMLnJ2LmRhdGEuVVJMEhIKCnBjb19p",
            "ZF9udW0YBSABKA0SFAoMbmVlZHNfdXBkYXRlGAYgASgIEicKC3VwZGF0ZV9k",
            "YXRlGAcgASgLMhIucnYuZGF0YS5UaW1lc3RhbXASEgoKcGNvX2lkX3N0chgI",
            "IAEoCRq1AgoIU29uZ0l0ZW0SEgoKcGNvX2lkX251bRgBIAEoDRIaChJhcnJh",
            "bmdlbWVudF9pZF9udW0YAiABKA0SKAoEY2NsaRgDIAEoCzIaLnJ2LmRhdGEu",
            "UHJlc2VudGF0aW9uLkNDTEkSSAoIc2VxdWVuY2UYBCABKAsyNi5ydi5kYXRh",
            "LlBsYW5uaW5nQ2VudGVyUGxhbi5QbGFuSXRlbS5Tb25nSXRlbS5TZXF1ZW5j",
            "ZRISCgpwY29faWRfc3RyGAUgASgJEhoKEmFycmFuZ2VtZW50X2lkX3N0chgG",
            "IAEoCRpVCghTZXF1ZW5jZRISCgpwY29faWRfbnVtGAEgASgNEgwKBG5hbWUY",
            "AiABKAkSEwoLZ3JvdXBfbmFtZXMYAyADKAkSEgoKcGNvX2lkX3N0chgEIAEo",
            "CSJ1CgxQbGFuSXRlbVR5cGUSFwoTUExBTl9JVEVNX1RZUEVfSVRFTRAAEhcK",
            "E1BMQU5fSVRFTV9UWVBFX1NPTkcQARIYChRQTEFOX0lURU1fVFlQRV9NRURJ",
            "QRACEhkKFVBMQU5fSVRFTV9UWVBFX0hFQURFUhADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.BasicTypesReflection.Descriptor, global::Rv.Data.TimestampReflection.Descriptor, global::Rv.Data.PresentationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlanningCenterPlan), global::Rv.Data.PlanningCenterPlan.Parser, new[]{ "PlanIdNum", "ParentIdNum", "SeriesTitle", "PlanTitle", "DateList", "CreatedDate", "UpdateDate", "LastUpdateCheckDate", "PlanIdStr", "ParentIdStr" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlanningCenterPlan.Types.PlanItem), global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Parser, new[]{ "ItemType", "PcoIdNum", "ServiceIdNum", "ParentIdNum", "Name", "Attachments", "UpdateDate", "LinkedSong", "PcoIdStr", "ServiceIdStr", "ParentIdStr" }, null, new[]{ typeof(global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment), global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment.Parser, new[]{ "Name", "Url", "CreatedDate", "LinkedPath", "PcoIdNum", "NeedsUpdate", "UpdateDate", "PcoIdStr" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem), global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Parser, new[]{ "PcoIdNum", "ArrangementIdNum", "Ccli", "Sequence", "PcoIdStr", "ArrangementIdStr" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence), global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence.Parser, new[]{ "PcoIdNum", "Name", "GroupNames", "PcoIdStr" }, null, null, null, null)})})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlanningCenterPlan : pb::IMessage<PlanningCenterPlan>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlanningCenterPlan> _parser = new pb::MessageParser<PlanningCenterPlan>(() => new PlanningCenterPlan());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlanningCenterPlan> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.PlanningCenterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanningCenterPlan() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanningCenterPlan(PlanningCenterPlan other) : this() {
      planIdNum_ = other.planIdNum_;
      parentIdNum_ = other.parentIdNum_;
      seriesTitle_ = other.seriesTitle_;
      planTitle_ = other.planTitle_;
      dateList_ = other.dateList_;
      createdDate_ = other.createdDate_ != null ? other.createdDate_.Clone() : null;
      updateDate_ = other.updateDate_ != null ? other.updateDate_.Clone() : null;
      lastUpdateCheckDate_ = other.lastUpdateCheckDate_ != null ? other.lastUpdateCheckDate_.Clone() : null;
      planIdStr_ = other.planIdStr_;
      parentIdStr_ = other.parentIdStr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanningCenterPlan Clone() {
      return new PlanningCenterPlan(this);
    }

    /// <summary>Field number for the "plan_id_num" field.</summary>
    public const int PlanIdNumFieldNumber = 1;
    private uint planIdNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PlanIdNum {
      get { return planIdNum_; }
      set {
        planIdNum_ = value;
      }
    }

    /// <summary>Field number for the "parent_id_num" field.</summary>
    public const int ParentIdNumFieldNumber = 2;
    private uint parentIdNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ParentIdNum {
      get { return parentIdNum_; }
      set {
        parentIdNum_ = value;
      }
    }

    /// <summary>Field number for the "series_title" field.</summary>
    public const int SeriesTitleFieldNumber = 3;
    private string seriesTitle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SeriesTitle {
      get { return seriesTitle_; }
      set {
        seriesTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plan_title" field.</summary>
    public const int PlanTitleFieldNumber = 4;
    private string planTitle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlanTitle {
      get { return planTitle_; }
      set {
        planTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_list" field.</summary>
    public const int DateListFieldNumber = 5;
    private string dateList_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateList {
      get { return dateList_; }
      set {
        dateList_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_date" field.</summary>
    public const int CreatedDateFieldNumber = 6;
    private global::Rv.Data.Timestamp createdDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Timestamp CreatedDate {
      get { return createdDate_; }
      set {
        createdDate_ = value;
      }
    }

    /// <summary>Field number for the "update_date" field.</summary>
    public const int UpdateDateFieldNumber = 7;
    private global::Rv.Data.Timestamp updateDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Timestamp UpdateDate {
      get { return updateDate_; }
      set {
        updateDate_ = value;
      }
    }

    /// <summary>Field number for the "last_update_check_date" field.</summary>
    public const int LastUpdateCheckDateFieldNumber = 8;
    private global::Rv.Data.Timestamp lastUpdateCheckDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Timestamp LastUpdateCheckDate {
      get { return lastUpdateCheckDate_; }
      set {
        lastUpdateCheckDate_ = value;
      }
    }

    /// <summary>Field number for the "plan_id_str" field.</summary>
    public const int PlanIdStrFieldNumber = 9;
    private string planIdStr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlanIdStr {
      get { return planIdStr_; }
      set {
        planIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parent_id_str" field.</summary>
    public const int ParentIdStrFieldNumber = 10;
    private string parentIdStr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentIdStr {
      get { return parentIdStr_; }
      set {
        parentIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlanningCenterPlan);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlanningCenterPlan other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlanIdNum != other.PlanIdNum) return false;
      if (ParentIdNum != other.ParentIdNum) return false;
      if (SeriesTitle != other.SeriesTitle) return false;
      if (PlanTitle != other.PlanTitle) return false;
      if (DateList != other.DateList) return false;
      if (!object.Equals(CreatedDate, other.CreatedDate)) return false;
      if (!object.Equals(UpdateDate, other.UpdateDate)) return false;
      if (!object.Equals(LastUpdateCheckDate, other.LastUpdateCheckDate)) return false;
      if (PlanIdStr != other.PlanIdStr) return false;
      if (ParentIdStr != other.ParentIdStr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlanIdNum != 0) hash ^= PlanIdNum.GetHashCode();
      if (ParentIdNum != 0) hash ^= ParentIdNum.GetHashCode();
      if (SeriesTitle.Length != 0) hash ^= SeriesTitle.GetHashCode();
      if (PlanTitle.Length != 0) hash ^= PlanTitle.GetHashCode();
      if (DateList.Length != 0) hash ^= DateList.GetHashCode();
      if (createdDate_ != null) hash ^= CreatedDate.GetHashCode();
      if (updateDate_ != null) hash ^= UpdateDate.GetHashCode();
      if (lastUpdateCheckDate_ != null) hash ^= LastUpdateCheckDate.GetHashCode();
      if (PlanIdStr.Length != 0) hash ^= PlanIdStr.GetHashCode();
      if (ParentIdStr.Length != 0) hash ^= ParentIdStr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlanIdNum != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlanIdNum);
      }
      if (ParentIdNum != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ParentIdNum);
      }
      if (SeriesTitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SeriesTitle);
      }
      if (PlanTitle.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PlanTitle);
      }
      if (DateList.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DateList);
      }
      if (createdDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CreatedDate);
      }
      if (updateDate_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(UpdateDate);
      }
      if (lastUpdateCheckDate_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(LastUpdateCheckDate);
      }
      if (PlanIdStr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PlanIdStr);
      }
      if (ParentIdStr.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ParentIdStr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlanIdNum != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlanIdNum);
      }
      if (ParentIdNum != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ParentIdNum);
      }
      if (SeriesTitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SeriesTitle);
      }
      if (PlanTitle.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PlanTitle);
      }
      if (DateList.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DateList);
      }
      if (createdDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CreatedDate);
      }
      if (updateDate_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(UpdateDate);
      }
      if (lastUpdateCheckDate_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(LastUpdateCheckDate);
      }
      if (PlanIdStr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PlanIdStr);
      }
      if (ParentIdStr.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ParentIdStr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlanIdNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlanIdNum);
      }
      if (ParentIdNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ParentIdNum);
      }
      if (SeriesTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SeriesTitle);
      }
      if (PlanTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlanTitle);
      }
      if (DateList.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateList);
      }
      if (createdDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedDate);
      }
      if (updateDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateDate);
      }
      if (lastUpdateCheckDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdateCheckDate);
      }
      if (PlanIdStr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlanIdStr);
      }
      if (ParentIdStr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentIdStr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlanningCenterPlan other) {
      if (other == null) {
        return;
      }
      if (other.PlanIdNum != 0) {
        PlanIdNum = other.PlanIdNum;
      }
      if (other.ParentIdNum != 0) {
        ParentIdNum = other.ParentIdNum;
      }
      if (other.SeriesTitle.Length != 0) {
        SeriesTitle = other.SeriesTitle;
      }
      if (other.PlanTitle.Length != 0) {
        PlanTitle = other.PlanTitle;
      }
      if (other.DateList.Length != 0) {
        DateList = other.DateList;
      }
      if (other.createdDate_ != null) {
        if (createdDate_ == null) {
          CreatedDate = new global::Rv.Data.Timestamp();
        }
        CreatedDate.MergeFrom(other.CreatedDate);
      }
      if (other.updateDate_ != null) {
        if (updateDate_ == null) {
          UpdateDate = new global::Rv.Data.Timestamp();
        }
        UpdateDate.MergeFrom(other.UpdateDate);
      }
      if (other.lastUpdateCheckDate_ != null) {
        if (lastUpdateCheckDate_ == null) {
          LastUpdateCheckDate = new global::Rv.Data.Timestamp();
        }
        LastUpdateCheckDate.MergeFrom(other.LastUpdateCheckDate);
      }
      if (other.PlanIdStr.Length != 0) {
        PlanIdStr = other.PlanIdStr;
      }
      if (other.ParentIdStr.Length != 0) {
        ParentIdStr = other.ParentIdStr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlanIdNum = input.ReadUInt32();
            break;
          }
          case 16: {
            ParentIdNum = input.ReadUInt32();
            break;
          }
          case 26: {
            SeriesTitle = input.ReadString();
            break;
          }
          case 34: {
            PlanTitle = input.ReadString();
            break;
          }
          case 42: {
            DateList = input.ReadString();
            break;
          }
          case 50: {
            if (createdDate_ == null) {
              CreatedDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(CreatedDate);
            break;
          }
          case 58: {
            if (updateDate_ == null) {
              UpdateDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(UpdateDate);
            break;
          }
          case 66: {
            if (lastUpdateCheckDate_ == null) {
              LastUpdateCheckDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(LastUpdateCheckDate);
            break;
          }
          case 74: {
            PlanIdStr = input.ReadString();
            break;
          }
          case 82: {
            ParentIdStr = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlanIdNum = input.ReadUInt32();
            break;
          }
          case 16: {
            ParentIdNum = input.ReadUInt32();
            break;
          }
          case 26: {
            SeriesTitle = input.ReadString();
            break;
          }
          case 34: {
            PlanTitle = input.ReadString();
            break;
          }
          case 42: {
            DateList = input.ReadString();
            break;
          }
          case 50: {
            if (createdDate_ == null) {
              CreatedDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(CreatedDate);
            break;
          }
          case 58: {
            if (updateDate_ == null) {
              UpdateDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(UpdateDate);
            break;
          }
          case 66: {
            if (lastUpdateCheckDate_ == null) {
              LastUpdateCheckDate = new global::Rv.Data.Timestamp();
            }
            input.ReadMessage(LastUpdateCheckDate);
            break;
          }
          case 74: {
            PlanIdStr = input.ReadString();
            break;
          }
          case 82: {
            ParentIdStr = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PlanningCenterPlan message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class PlanItem : pb::IMessage<PlanItem>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PlanItem> _parser = new pb::MessageParser<PlanItem>(() => new PlanItem());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PlanItem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.PlanningCenterPlan.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlanItem() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlanItem(PlanItem other) : this() {
          itemType_ = other.itemType_;
          pcoIdNum_ = other.pcoIdNum_;
          serviceIdNum_ = other.serviceIdNum_;
          parentIdNum_ = other.parentIdNum_;
          name_ = other.name_;
          attachments_ = other.attachments_.Clone();
          updateDate_ = other.updateDate_ != null ? other.updateDate_.Clone() : null;
          linkedSong_ = other.linkedSong_ != null ? other.linkedSong_.Clone() : null;
          pcoIdStr_ = other.pcoIdStr_;
          serviceIdStr_ = other.serviceIdStr_;
          parentIdStr_ = other.parentIdStr_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlanItem Clone() {
          return new PlanItem(this);
        }

        /// <summary>Field number for the "item_type" field.</summary>
        public const int ItemTypeFieldNumber = 1;
        private global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType itemType_ = global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType ItemType {
          get { return itemType_; }
          set {
            itemType_ = value;
          }
        }

        /// <summary>Field number for the "pco_id_num" field.</summary>
        public const int PcoIdNumFieldNumber = 2;
        private uint pcoIdNum_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint PcoIdNum {
          get { return pcoIdNum_; }
          set {
            pcoIdNum_ = value;
          }
        }

        /// <summary>Field number for the "service_id_num" field.</summary>
        public const int ServiceIdNumFieldNumber = 3;
        private uint serviceIdNum_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ServiceIdNum {
          get { return serviceIdNum_; }
          set {
            serviceIdNum_ = value;
          }
        }

        /// <summary>Field number for the "parent_id_num" field.</summary>
        public const int ParentIdNumFieldNumber = 4;
        private uint parentIdNum_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ParentIdNum {
          get { return parentIdNum_; }
          set {
            parentIdNum_ = value;
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 5;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "attachments" field.</summary>
        public const int AttachmentsFieldNumber = 6;
        private static readonly pb::FieldCodec<global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment> _repeated_attachments_codec
            = pb::FieldCodec.ForMessage(50, global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment.Parser);
        private readonly pbc::RepeatedField<global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment> attachments_ = new pbc::RepeatedField<global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.Attachment> Attachments {
          get { return attachments_; }
        }

        /// <summary>Field number for the "update_date" field.</summary>
        public const int UpdateDateFieldNumber = 7;
        private global::Rv.Data.Timestamp updateDate_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.Timestamp UpdateDate {
          get { return updateDate_; }
          set {
            updateDate_ = value;
          }
        }

        /// <summary>Field number for the "linked_song" field.</summary>
        public const int LinkedSongFieldNumber = 8;
        private global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem linkedSong_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem LinkedSong {
          get { return linkedSong_; }
          set {
            linkedSong_ = value;
          }
        }

        /// <summary>Field number for the "pco_id_str" field.</summary>
        public const int PcoIdStrFieldNumber = 9;
        private string pcoIdStr_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string PcoIdStr {
          get { return pcoIdStr_; }
          set {
            pcoIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "service_id_str" field.</summary>
        public const int ServiceIdStrFieldNumber = 10;
        private string serviceIdStr_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServiceIdStr {
          get { return serviceIdStr_; }
          set {
            serviceIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "parent_id_str" field.</summary>
        public const int ParentIdStrFieldNumber = 11;
        private string parentIdStr_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ParentIdStr {
          get { return parentIdStr_; }
          set {
            parentIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as PlanItem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PlanItem other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ItemType != other.ItemType) return false;
          if (PcoIdNum != other.PcoIdNum) return false;
          if (ServiceIdNum != other.ServiceIdNum) return false;
          if (ParentIdNum != other.ParentIdNum) return false;
          if (Name != other.Name) return false;
          if(!attachments_.Equals(other.attachments_)) return false;
          if (!object.Equals(UpdateDate, other.UpdateDate)) return false;
          if (!object.Equals(LinkedSong, other.LinkedSong)) return false;
          if (PcoIdStr != other.PcoIdStr) return false;
          if (ServiceIdStr != other.ServiceIdStr) return false;
          if (ParentIdStr != other.ParentIdStr) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ItemType != global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item) hash ^= ItemType.GetHashCode();
          if (PcoIdNum != 0) hash ^= PcoIdNum.GetHashCode();
          if (ServiceIdNum != 0) hash ^= ServiceIdNum.GetHashCode();
          if (ParentIdNum != 0) hash ^= ParentIdNum.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          hash ^= attachments_.GetHashCode();
          if (updateDate_ != null) hash ^= UpdateDate.GetHashCode();
          if (linkedSong_ != null) hash ^= LinkedSong.GetHashCode();
          if (PcoIdStr.Length != 0) hash ^= PcoIdStr.GetHashCode();
          if (ServiceIdStr.Length != 0) hash ^= ServiceIdStr.GetHashCode();
          if (ParentIdStr.Length != 0) hash ^= ParentIdStr.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ItemType != global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item) {
            output.WriteRawTag(8);
            output.WriteEnum((int) ItemType);
          }
          if (PcoIdNum != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(PcoIdNum);
          }
          if (ServiceIdNum != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ServiceIdNum);
          }
          if (ParentIdNum != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(ParentIdNum);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(Name);
          }
          attachments_.WriteTo(output, _repeated_attachments_codec);
          if (updateDate_ != null) {
            output.WriteRawTag(58);
            output.WriteMessage(UpdateDate);
          }
          if (linkedSong_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(LinkedSong);
          }
          if (PcoIdStr.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(PcoIdStr);
          }
          if (ServiceIdStr.Length != 0) {
            output.WriteRawTag(82);
            output.WriteString(ServiceIdStr);
          }
          if (ParentIdStr.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(ParentIdStr);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ItemType != global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item) {
            output.WriteRawTag(8);
            output.WriteEnum((int) ItemType);
          }
          if (PcoIdNum != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(PcoIdNum);
          }
          if (ServiceIdNum != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ServiceIdNum);
          }
          if (ParentIdNum != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(ParentIdNum);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(Name);
          }
          attachments_.WriteTo(ref output, _repeated_attachments_codec);
          if (updateDate_ != null) {
            output.WriteRawTag(58);
            output.WriteMessage(UpdateDate);
          }
          if (linkedSong_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(LinkedSong);
          }
          if (PcoIdStr.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(PcoIdStr);
          }
          if (ServiceIdStr.Length != 0) {
            output.WriteRawTag(82);
            output.WriteString(ServiceIdStr);
          }
          if (ParentIdStr.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(ParentIdStr);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ItemType != global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
          }
          if (PcoIdNum != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PcoIdNum);
          }
          if (ServiceIdNum != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ServiceIdNum);
          }
          if (ParentIdNum != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ParentIdNum);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          size += attachments_.CalculateSize(_repeated_attachments_codec);
          if (updateDate_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateDate);
          }
          if (linkedSong_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(LinkedSong);
          }
          if (PcoIdStr.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PcoIdStr);
          }
          if (ServiceIdStr.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceIdStr);
          }
          if (ParentIdStr.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentIdStr);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PlanItem other) {
          if (other == null) {
            return;
          }
          if (other.ItemType != global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType.Item) {
            ItemType = other.ItemType;
          }
          if (other.PcoIdNum != 0) {
            PcoIdNum = other.PcoIdNum;
          }
          if (other.ServiceIdNum != 0) {
            ServiceIdNum = other.ServiceIdNum;
          }
          if (other.ParentIdNum != 0) {
            ParentIdNum = other.ParentIdNum;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          attachments_.Add(other.attachments_);
          if (other.updateDate_ != null) {
            if (updateDate_ == null) {
              UpdateDate = new global::Rv.Data.Timestamp();
            }
            UpdateDate.MergeFrom(other.UpdateDate);
          }
          if (other.linkedSong_ != null) {
            if (linkedSong_ == null) {
              LinkedSong = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem();
            }
            LinkedSong.MergeFrom(other.LinkedSong);
          }
          if (other.PcoIdStr.Length != 0) {
            PcoIdStr = other.PcoIdStr;
          }
          if (other.ServiceIdStr.Length != 0) {
            ServiceIdStr = other.ServiceIdStr;
          }
          if (other.ParentIdStr.Length != 0) {
            ParentIdStr = other.ParentIdStr;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ItemType = (global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType) input.ReadEnum();
                break;
              }
              case 16: {
                PcoIdNum = input.ReadUInt32();
                break;
              }
              case 24: {
                ServiceIdNum = input.ReadUInt32();
                break;
              }
              case 32: {
                ParentIdNum = input.ReadUInt32();
                break;
              }
              case 42: {
                Name = input.ReadString();
                break;
              }
              case 50: {
                attachments_.AddEntriesFrom(input, _repeated_attachments_codec);
                break;
              }
              case 58: {
                if (updateDate_ == null) {
                  UpdateDate = new global::Rv.Data.Timestamp();
                }
                input.ReadMessage(UpdateDate);
                break;
              }
              case 66: {
                if (linkedSong_ == null) {
                  LinkedSong = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem();
                }
                input.ReadMessage(LinkedSong);
                break;
              }
              case 74: {
                PcoIdStr = input.ReadString();
                break;
              }
              case 82: {
                ServiceIdStr = input.ReadString();
                break;
              }
              case 90: {
                ParentIdStr = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ItemType = (global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.PlanItemType) input.ReadEnum();
                break;
              }
              case 16: {
                PcoIdNum = input.ReadUInt32();
                break;
              }
              case 24: {
                ServiceIdNum = input.ReadUInt32();
                break;
              }
              case 32: {
                ParentIdNum = input.ReadUInt32();
                break;
              }
              case 42: {
                Name = input.ReadString();
                break;
              }
              case 50: {
                attachments_.AddEntriesFrom(ref input, _repeated_attachments_codec);
                break;
              }
              case 58: {
                if (updateDate_ == null) {
                  UpdateDate = new global::Rv.Data.Timestamp();
                }
                input.ReadMessage(UpdateDate);
                break;
              }
              case 66: {
                if (linkedSong_ == null) {
                  LinkedSong = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem();
                }
                input.ReadMessage(LinkedSong);
                break;
              }
              case 74: {
                PcoIdStr = input.ReadString();
                break;
              }
              case 82: {
                ServiceIdStr = input.ReadString();
                break;
              }
              case 90: {
                ParentIdStr = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the PlanItem message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum PlanItemType {
            [pbr::OriginalName("PLAN_ITEM_TYPE_ITEM")] Item = 0,
            [pbr::OriginalName("PLAN_ITEM_TYPE_SONG")] Song = 1,
            [pbr::OriginalName("PLAN_ITEM_TYPE_MEDIA")] Media = 2,
            [pbr::OriginalName("PLAN_ITEM_TYPE_HEADER")] Header = 3,
          }

          public sealed partial class Attachment : pb::IMessage<Attachment>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Attachment> _parser = new pb::MessageParser<Attachment>(() => new Attachment());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Attachment> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Attachment() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Attachment(Attachment other) : this() {
              name_ = other.name_;
              url_ = other.url_ != null ? other.url_.Clone() : null;
              createdDate_ = other.createdDate_ != null ? other.createdDate_.Clone() : null;
              linkedPath_ = other.linkedPath_ != null ? other.linkedPath_.Clone() : null;
              pcoIdNum_ = other.pcoIdNum_;
              needsUpdate_ = other.needsUpdate_;
              updateDate_ = other.updateDate_ != null ? other.updateDate_.Clone() : null;
              pcoIdStr_ = other.pcoIdStr_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Attachment Clone() {
              return new Attachment(this);
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 1;
            private string name_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Name {
              get { return name_; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "url" field.</summary>
            public const int UrlFieldNumber = 2;
            private global::Rv.Data.URL url_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.URL Url {
              get { return url_; }
              set {
                url_ = value;
              }
            }

            /// <summary>Field number for the "created_date" field.</summary>
            public const int CreatedDateFieldNumber = 3;
            private global::Rv.Data.Timestamp createdDate_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.Timestamp CreatedDate {
              get { return createdDate_; }
              set {
                createdDate_ = value;
              }
            }

            /// <summary>Field number for the "linked_path" field.</summary>
            public const int LinkedPathFieldNumber = 4;
            private global::Rv.Data.URL linkedPath_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.URL LinkedPath {
              get { return linkedPath_; }
              set {
                linkedPath_ = value;
              }
            }

            /// <summary>Field number for the "pco_id_num" field.</summary>
            public const int PcoIdNumFieldNumber = 5;
            private uint pcoIdNum_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint PcoIdNum {
              get { return pcoIdNum_; }
              set {
                pcoIdNum_ = value;
              }
            }

            /// <summary>Field number for the "needs_update" field.</summary>
            public const int NeedsUpdateFieldNumber = 6;
            private bool needsUpdate_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool NeedsUpdate {
              get { return needsUpdate_; }
              set {
                needsUpdate_ = value;
              }
            }

            /// <summary>Field number for the "update_date" field.</summary>
            public const int UpdateDateFieldNumber = 7;
            private global::Rv.Data.Timestamp updateDate_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.Timestamp UpdateDate {
              get { return updateDate_; }
              set {
                updateDate_ = value;
              }
            }

            /// <summary>Field number for the "pco_id_str" field.</summary>
            public const int PcoIdStrFieldNumber = 8;
            private string pcoIdStr_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string PcoIdStr {
              get { return pcoIdStr_; }
              set {
                pcoIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Attachment);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Attachment other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Name != other.Name) return false;
              if (!object.Equals(Url, other.Url)) return false;
              if (!object.Equals(CreatedDate, other.CreatedDate)) return false;
              if (!object.Equals(LinkedPath, other.LinkedPath)) return false;
              if (PcoIdNum != other.PcoIdNum) return false;
              if (NeedsUpdate != other.NeedsUpdate) return false;
              if (!object.Equals(UpdateDate, other.UpdateDate)) return false;
              if (PcoIdStr != other.PcoIdStr) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Name.Length != 0) hash ^= Name.GetHashCode();
              if (url_ != null) hash ^= Url.GetHashCode();
              if (createdDate_ != null) hash ^= CreatedDate.GetHashCode();
              if (linkedPath_ != null) hash ^= LinkedPath.GetHashCode();
              if (PcoIdNum != 0) hash ^= PcoIdNum.GetHashCode();
              if (NeedsUpdate != false) hash ^= NeedsUpdate.GetHashCode();
              if (updateDate_ != null) hash ^= UpdateDate.GetHashCode();
              if (PcoIdStr.Length != 0) hash ^= PcoIdStr.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Name.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Name);
              }
              if (url_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Url);
              }
              if (createdDate_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(CreatedDate);
              }
              if (linkedPath_ != null) {
                output.WriteRawTag(34);
                output.WriteMessage(LinkedPath);
              }
              if (PcoIdNum != 0) {
                output.WriteRawTag(40);
                output.WriteUInt32(PcoIdNum);
              }
              if (NeedsUpdate != false) {
                output.WriteRawTag(48);
                output.WriteBool(NeedsUpdate);
              }
              if (updateDate_ != null) {
                output.WriteRawTag(58);
                output.WriteMessage(UpdateDate);
              }
              if (PcoIdStr.Length != 0) {
                output.WriteRawTag(66);
                output.WriteString(PcoIdStr);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Name.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Name);
              }
              if (url_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Url);
              }
              if (createdDate_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(CreatedDate);
              }
              if (linkedPath_ != null) {
                output.WriteRawTag(34);
                output.WriteMessage(LinkedPath);
              }
              if (PcoIdNum != 0) {
                output.WriteRawTag(40);
                output.WriteUInt32(PcoIdNum);
              }
              if (NeedsUpdate != false) {
                output.WriteRawTag(48);
                output.WriteBool(NeedsUpdate);
              }
              if (updateDate_ != null) {
                output.WriteRawTag(58);
                output.WriteMessage(UpdateDate);
              }
              if (PcoIdStr.Length != 0) {
                output.WriteRawTag(66);
                output.WriteString(PcoIdStr);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Name.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (url_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Url);
              }
              if (createdDate_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedDate);
              }
              if (linkedPath_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(LinkedPath);
              }
              if (PcoIdNum != 0) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PcoIdNum);
              }
              if (NeedsUpdate != false) {
                size += 1 + 1;
              }
              if (updateDate_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateDate);
              }
              if (PcoIdStr.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(PcoIdStr);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Attachment other) {
              if (other == null) {
                return;
              }
              if (other.Name.Length != 0) {
                Name = other.Name;
              }
              if (other.url_ != null) {
                if (url_ == null) {
                  Url = new global::Rv.Data.URL();
                }
                Url.MergeFrom(other.Url);
              }
              if (other.createdDate_ != null) {
                if (createdDate_ == null) {
                  CreatedDate = new global::Rv.Data.Timestamp();
                }
                CreatedDate.MergeFrom(other.CreatedDate);
              }
              if (other.linkedPath_ != null) {
                if (linkedPath_ == null) {
                  LinkedPath = new global::Rv.Data.URL();
                }
                LinkedPath.MergeFrom(other.LinkedPath);
              }
              if (other.PcoIdNum != 0) {
                PcoIdNum = other.PcoIdNum;
              }
              if (other.NeedsUpdate != false) {
                NeedsUpdate = other.NeedsUpdate;
              }
              if (other.updateDate_ != null) {
                if (updateDate_ == null) {
                  UpdateDate = new global::Rv.Data.Timestamp();
                }
                UpdateDate.MergeFrom(other.UpdateDate);
              }
              if (other.PcoIdStr.Length != 0) {
                PcoIdStr = other.PcoIdStr;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Name = input.ReadString();
                    break;
                  }
                  case 18: {
                    if (url_ == null) {
                      Url = new global::Rv.Data.URL();
                    }
                    input.ReadMessage(Url);
                    break;
                  }
                  case 26: {
                    if (createdDate_ == null) {
                      CreatedDate = new global::Rv.Data.Timestamp();
                    }
                    input.ReadMessage(CreatedDate);
                    break;
                  }
                  case 34: {
                    if (linkedPath_ == null) {
                      LinkedPath = new global::Rv.Data.URL();
                    }
                    input.ReadMessage(LinkedPath);
                    break;
                  }
                  case 40: {
                    PcoIdNum = input.ReadUInt32();
                    break;
                  }
                  case 48: {
                    NeedsUpdate = input.ReadBool();
                    break;
                  }
                  case 58: {
                    if (updateDate_ == null) {
                      UpdateDate = new global::Rv.Data.Timestamp();
                    }
                    input.ReadMessage(UpdateDate);
                    break;
                  }
                  case 66: {
                    PcoIdStr = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    Name = input.ReadString();
                    break;
                  }
                  case 18: {
                    if (url_ == null) {
                      Url = new global::Rv.Data.URL();
                    }
                    input.ReadMessage(Url);
                    break;
                  }
                  case 26: {
                    if (createdDate_ == null) {
                      CreatedDate = new global::Rv.Data.Timestamp();
                    }
                    input.ReadMessage(CreatedDate);
                    break;
                  }
                  case 34: {
                    if (linkedPath_ == null) {
                      LinkedPath = new global::Rv.Data.URL();
                    }
                    input.ReadMessage(LinkedPath);
                    break;
                  }
                  case 40: {
                    PcoIdNum = input.ReadUInt32();
                    break;
                  }
                  case 48: {
                    NeedsUpdate = input.ReadBool();
                    break;
                  }
                  case 58: {
                    if (updateDate_ == null) {
                      UpdateDate = new global::Rv.Data.Timestamp();
                    }
                    input.ReadMessage(UpdateDate);
                    break;
                  }
                  case 66: {
                    PcoIdStr = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

          public sealed partial class SongItem : pb::IMessage<SongItem>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<SongItem> _parser = new pb::MessageParser<SongItem>(() => new SongItem());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<SongItem> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SongItem() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SongItem(SongItem other) : this() {
              pcoIdNum_ = other.pcoIdNum_;
              arrangementIdNum_ = other.arrangementIdNum_;
              ccli_ = other.ccli_ != null ? other.ccli_.Clone() : null;
              sequence_ = other.sequence_ != null ? other.sequence_.Clone() : null;
              pcoIdStr_ = other.pcoIdStr_;
              arrangementIdStr_ = other.arrangementIdStr_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SongItem Clone() {
              return new SongItem(this);
            }

            /// <summary>Field number for the "pco_id_num" field.</summary>
            public const int PcoIdNumFieldNumber = 1;
            private uint pcoIdNum_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint PcoIdNum {
              get { return pcoIdNum_; }
              set {
                pcoIdNum_ = value;
              }
            }

            /// <summary>Field number for the "arrangement_id_num" field.</summary>
            public const int ArrangementIdNumFieldNumber = 2;
            private uint arrangementIdNum_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint ArrangementIdNum {
              get { return arrangementIdNum_; }
              set {
                arrangementIdNum_ = value;
              }
            }

            /// <summary>Field number for the "ccli" field.</summary>
            public const int CcliFieldNumber = 3;
            private global::Rv.Data.Presentation.Types.CCLI ccli_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.Presentation.Types.CCLI Ccli {
              get { return ccli_; }
              set {
                ccli_ = value;
              }
            }

            /// <summary>Field number for the "sequence" field.</summary>
            public const int SequenceFieldNumber = 4;
            private global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence sequence_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence Sequence {
              get { return sequence_; }
              set {
                sequence_ = value;
              }
            }

            /// <summary>Field number for the "pco_id_str" field.</summary>
            public const int PcoIdStrFieldNumber = 5;
            private string pcoIdStr_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string PcoIdStr {
              get { return pcoIdStr_; }
              set {
                pcoIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "arrangement_id_str" field.</summary>
            public const int ArrangementIdStrFieldNumber = 6;
            private string arrangementIdStr_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string ArrangementIdStr {
              get { return arrangementIdStr_; }
              set {
                arrangementIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as SongItem);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(SongItem other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (PcoIdNum != other.PcoIdNum) return false;
              if (ArrangementIdNum != other.ArrangementIdNum) return false;
              if (!object.Equals(Ccli, other.Ccli)) return false;
              if (!object.Equals(Sequence, other.Sequence)) return false;
              if (PcoIdStr != other.PcoIdStr) return false;
              if (ArrangementIdStr != other.ArrangementIdStr) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (PcoIdNum != 0) hash ^= PcoIdNum.GetHashCode();
              if (ArrangementIdNum != 0) hash ^= ArrangementIdNum.GetHashCode();
              if (ccli_ != null) hash ^= Ccli.GetHashCode();
              if (sequence_ != null) hash ^= Sequence.GetHashCode();
              if (PcoIdStr.Length != 0) hash ^= PcoIdStr.GetHashCode();
              if (ArrangementIdStr.Length != 0) hash ^= ArrangementIdStr.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (PcoIdNum != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(PcoIdNum);
              }
              if (ArrangementIdNum != 0) {
                output.WriteRawTag(16);
                output.WriteUInt32(ArrangementIdNum);
              }
              if (ccli_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(Ccli);
              }
              if (sequence_ != null) {
                output.WriteRawTag(34);
                output.WriteMessage(Sequence);
              }
              if (PcoIdStr.Length != 0) {
                output.WriteRawTag(42);
                output.WriteString(PcoIdStr);
              }
              if (ArrangementIdStr.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(ArrangementIdStr);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (PcoIdNum != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(PcoIdNum);
              }
              if (ArrangementIdNum != 0) {
                output.WriteRawTag(16);
                output.WriteUInt32(ArrangementIdNum);
              }
              if (ccli_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(Ccli);
              }
              if (sequence_ != null) {
                output.WriteRawTag(34);
                output.WriteMessage(Sequence);
              }
              if (PcoIdStr.Length != 0) {
                output.WriteRawTag(42);
                output.WriteString(PcoIdStr);
              }
              if (ArrangementIdStr.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(ArrangementIdStr);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (PcoIdNum != 0) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PcoIdNum);
              }
              if (ArrangementIdNum != 0) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ArrangementIdNum);
              }
              if (ccli_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ccli);
              }
              if (sequence_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sequence);
              }
              if (PcoIdStr.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(PcoIdStr);
              }
              if (ArrangementIdStr.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ArrangementIdStr);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(SongItem other) {
              if (other == null) {
                return;
              }
              if (other.PcoIdNum != 0) {
                PcoIdNum = other.PcoIdNum;
              }
              if (other.ArrangementIdNum != 0) {
                ArrangementIdNum = other.ArrangementIdNum;
              }
              if (other.ccli_ != null) {
                if (ccli_ == null) {
                  Ccli = new global::Rv.Data.Presentation.Types.CCLI();
                }
                Ccli.MergeFrom(other.Ccli);
              }
              if (other.sequence_ != null) {
                if (sequence_ == null) {
                  Sequence = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence();
                }
                Sequence.MergeFrom(other.Sequence);
              }
              if (other.PcoIdStr.Length != 0) {
                PcoIdStr = other.PcoIdStr;
              }
              if (other.ArrangementIdStr.Length != 0) {
                ArrangementIdStr = other.ArrangementIdStr;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    PcoIdNum = input.ReadUInt32();
                    break;
                  }
                  case 16: {
                    ArrangementIdNum = input.ReadUInt32();
                    break;
                  }
                  case 26: {
                    if (ccli_ == null) {
                      Ccli = new global::Rv.Data.Presentation.Types.CCLI();
                    }
                    input.ReadMessage(Ccli);
                    break;
                  }
                  case 34: {
                    if (sequence_ == null) {
                      Sequence = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence();
                    }
                    input.ReadMessage(Sequence);
                    break;
                  }
                  case 42: {
                    PcoIdStr = input.ReadString();
                    break;
                  }
                  case 50: {
                    ArrangementIdStr = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    PcoIdNum = input.ReadUInt32();
                    break;
                  }
                  case 16: {
                    ArrangementIdNum = input.ReadUInt32();
                    break;
                  }
                  case 26: {
                    if (ccli_ == null) {
                      Ccli = new global::Rv.Data.Presentation.Types.CCLI();
                    }
                    input.ReadMessage(Ccli);
                    break;
                  }
                  case 34: {
                    if (sequence_ == null) {
                      Sequence = new global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Types.Sequence();
                    }
                    input.ReadMessage(Sequence);
                    break;
                  }
                  case 42: {
                    PcoIdStr = input.ReadString();
                    break;
                  }
                  case 50: {
                    ArrangementIdStr = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

            #region Nested types
            /// <summary>Container for nested types declared in the SongItem message type.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static partial class Types {
              public sealed partial class Sequence : pb::IMessage<Sequence>
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  , pb::IBufferMessage
              #endif
              {
                private static readonly pb::MessageParser<Sequence> _parser = new pb::MessageParser<Sequence>(() => new Sequence());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pb::MessageParser<Sequence> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Rv.Data.PlanningCenterPlan.Types.PlanItem.Types.SongItem.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Sequence() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Sequence(Sequence other) : this() {
                  pcoIdNum_ = other.pcoIdNum_;
                  name_ = other.name_;
                  groupNames_ = other.groupNames_.Clone();
                  pcoIdStr_ = other.pcoIdStr_;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public Sequence Clone() {
                  return new Sequence(this);
                }

                /// <summary>Field number for the "pco_id_num" field.</summary>
                public const int PcoIdNumFieldNumber = 1;
                private uint pcoIdNum_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public uint PcoIdNum {
                  get { return pcoIdNum_; }
                  set {
                    pcoIdNum_ = value;
                  }
                }

                /// <summary>Field number for the "name" field.</summary>
                public const int NameFieldNumber = 2;
                private string name_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public string Name {
                  get { return name_; }
                  set {
                    name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "group_names" field.</summary>
                public const int GroupNamesFieldNumber = 3;
                private static readonly pb::FieldCodec<string> _repeated_groupNames_codec
                    = pb::FieldCodec.ForString(26);
                private readonly pbc::RepeatedField<string> groupNames_ = new pbc::RepeatedField<string>();
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public pbc::RepeatedField<string> GroupNames {
                  get { return groupNames_; }
                }

                /// <summary>Field number for the "pco_id_str" field.</summary>
                public const int PcoIdStrFieldNumber = 4;
                private string pcoIdStr_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public string PcoIdStr {
                  get { return pcoIdStr_; }
                  set {
                    pcoIdStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override bool Equals(object other) {
                  return Equals(other as Sequence);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public bool Equals(Sequence other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (PcoIdNum != other.PcoIdNum) return false;
                  if (Name != other.Name) return false;
                  if(!groupNames_.Equals(other.groupNames_)) return false;
                  if (PcoIdStr != other.PcoIdStr) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override int GetHashCode() {
                  int hash = 1;
                  if (PcoIdNum != 0) hash ^= PcoIdNum.GetHashCode();
                  if (Name.Length != 0) hash ^= Name.GetHashCode();
                  hash ^= groupNames_.GetHashCode();
                  if (PcoIdStr.Length != 0) hash ^= PcoIdStr.GetHashCode();
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void WriteTo(pb::CodedOutputStream output) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  output.WriteRawMessage(this);
                #else
                  if (PcoIdNum != 0) {
                    output.WriteRawTag(8);
                    output.WriteUInt32(PcoIdNum);
                  }
                  if (Name.Length != 0) {
                    output.WriteRawTag(18);
                    output.WriteString(Name);
                  }
                  groupNames_.WriteTo(output, _repeated_groupNames_codec);
                  if (PcoIdStr.Length != 0) {
                    output.WriteRawTag(34);
                    output.WriteString(PcoIdStr);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                  if (PcoIdNum != 0) {
                    output.WriteRawTag(8);
                    output.WriteUInt32(PcoIdNum);
                  }
                  if (Name.Length != 0) {
                    output.WriteRawTag(18);
                    output.WriteString(Name);
                  }
                  groupNames_.WriteTo(ref output, _repeated_groupNames_codec);
                  if (PcoIdStr.Length != 0) {
                    output.WriteRawTag(34);
                    output.WriteString(PcoIdStr);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(ref output);
                  }
                }
                #endif

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int CalculateSize() {
                  int size = 0;
                  if (PcoIdNum != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PcoIdNum);
                  }
                  if (Name.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
                  }
                  size += groupNames_.CalculateSize(_repeated_groupNames_codec);
                  if (PcoIdStr.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(PcoIdStr);
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(Sequence other) {
                  if (other == null) {
                    return;
                  }
                  if (other.PcoIdNum != 0) {
                    PcoIdNum = other.PcoIdNum;
                  }
                  if (other.Name.Length != 0) {
                    Name = other.Name;
                  }
                  groupNames_.Add(other.groupNames_);
                  if (other.PcoIdStr.Length != 0) {
                    PcoIdStr = other.PcoIdStr;
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(pb::CodedInputStream input) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  input.ReadRawMessage(this);
                #else
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 8: {
                        PcoIdNum = input.ReadUInt32();
                        break;
                      }
                      case 18: {
                        Name = input.ReadString();
                        break;
                      }
                      case 26: {
                        groupNames_.AddEntriesFrom(input, _repeated_groupNames_codec);
                        break;
                      }
                      case 34: {
                        PcoIdStr = input.ReadString();
                        break;
                      }
                    }
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                      case 8: {
                        PcoIdNum = input.ReadUInt32();
                        break;
                      }
                      case 18: {
                        Name = input.ReadString();
                        break;
                      }
                      case 26: {
                        groupNames_.AddEntriesFrom(ref input, _repeated_groupNames_codec);
                        break;
                      }
                      case 34: {
                        PcoIdStr = input.ReadString();
                        break;
                      }
                    }
                  }
                }
                #endif

              }

            }
            #endregion

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
