// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: background.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from background.proto</summary>
  public static partial class BackgroundReflection {

    #region Descriptor
    /// <summary>File descriptor for background.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BackgroundReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBiYWNrZ3JvdW5kLnByb3RvEgdydi5kYXRhGhJncmFwaGljc0RhdGEucHJv",
            "dG8aEGJhc2ljVHlwZXMucHJvdG8ieQoKQmFja2dyb3VuZBISCgppc19lbmFi",
            "bGVkGAMgASgIEh8KBWNvbG9yGAEgASgLMg4ucnYuZGF0YS5Db2xvckgAEi4K",
            "CGdyYWRpZW50GAIgASgLMhoucnYuZGF0YS5HcmFwaGljcy5HcmFkaWVudEgA",
            "QgYKBEZpbGxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.GraphicsDataReflection.Descriptor, global::Rv.Data.BasicTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.Background), global::Rv.Data.Background.Parser, new[]{ "IsEnabled", "Color", "Gradient" }, new[]{ "Fill" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Background : pb::IMessage<Background>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Background> _parser = new pb::MessageParser<Background>(() => new Background());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Background> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.BackgroundReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Background() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Background(Background other) : this() {
      isEnabled_ = other.isEnabled_;
      switch (other.FillCase) {
        case FillOneofCase.Color:
          Color = other.Color.Clone();
          break;
        case FillOneofCase.Gradient:
          Gradient = other.Gradient.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Background Clone() {
      return new Background(this);
    }

    /// <summary>Field number for the "is_enabled" field.</summary>
    public const int IsEnabledFieldNumber = 3;
    private bool isEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsEnabled {
      get { return isEnabled_; }
      set {
        isEnabled_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Color Color {
      get { return fillCase_ == FillOneofCase.Color ? (global::Rv.Data.Color) fill_ : null; }
      set {
        fill_ = value;
        fillCase_ = value == null ? FillOneofCase.None : FillOneofCase.Color;
      }
    }

    /// <summary>Field number for the "gradient" field.</summary>
    public const int GradientFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Graphics.Types.Gradient Gradient {
      get { return fillCase_ == FillOneofCase.Gradient ? (global::Rv.Data.Graphics.Types.Gradient) fill_ : null; }
      set {
        fill_ = value;
        fillCase_ = value == null ? FillOneofCase.None : FillOneofCase.Gradient;
      }
    }

    private object fill_;
    /// <summary>Enum of possible cases for the "Fill" oneof.</summary>
    public enum FillOneofCase {
      None = 0,
      Color = 1,
      Gradient = 2,
    }
    private FillOneofCase fillCase_ = FillOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FillOneofCase FillCase {
      get { return fillCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFill() {
      fillCase_ = FillOneofCase.None;
      fill_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Background);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Background other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsEnabled != other.IsEnabled) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (!object.Equals(Gradient, other.Gradient)) return false;
      if (FillCase != other.FillCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsEnabled != false) hash ^= IsEnabled.GetHashCode();
      if (fillCase_ == FillOneofCase.Color) hash ^= Color.GetHashCode();
      if (fillCase_ == FillOneofCase.Gradient) hash ^= Gradient.GetHashCode();
      hash ^= (int) fillCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (fillCase_ == FillOneofCase.Color) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (fillCase_ == FillOneofCase.Gradient) {
        output.WriteRawTag(18);
        output.WriteMessage(Gradient);
      }
      if (IsEnabled != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (fillCase_ == FillOneofCase.Color) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (fillCase_ == FillOneofCase.Gradient) {
        output.WriteRawTag(18);
        output.WriteMessage(Gradient);
      }
      if (IsEnabled != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsEnabled != false) {
        size += 1 + 1;
      }
      if (fillCase_ == FillOneofCase.Color) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (fillCase_ == FillOneofCase.Gradient) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gradient);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Background other) {
      if (other == null) {
        return;
      }
      if (other.IsEnabled != false) {
        IsEnabled = other.IsEnabled;
      }
      switch (other.FillCase) {
        case FillOneofCase.Color:
          if (Color == null) {
            Color = new global::Rv.Data.Color();
          }
          Color.MergeFrom(other.Color);
          break;
        case FillOneofCase.Gradient:
          if (Gradient == null) {
            Gradient = new global::Rv.Data.Graphics.Types.Gradient();
          }
          Gradient.MergeFrom(other.Gradient);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Rv.Data.Color subBuilder = new global::Rv.Data.Color();
            if (fillCase_ == FillOneofCase.Color) {
              subBuilder.MergeFrom(Color);
            }
            input.ReadMessage(subBuilder);
            Color = subBuilder;
            break;
          }
          case 18: {
            global::Rv.Data.Graphics.Types.Gradient subBuilder = new global::Rv.Data.Graphics.Types.Gradient();
            if (fillCase_ == FillOneofCase.Gradient) {
              subBuilder.MergeFrom(Gradient);
            }
            input.ReadMessage(subBuilder);
            Gradient = subBuilder;
            break;
          }
          case 24: {
            IsEnabled = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Rv.Data.Color subBuilder = new global::Rv.Data.Color();
            if (fillCase_ == FillOneofCase.Color) {
              subBuilder.MergeFrom(Color);
            }
            input.ReadMessage(subBuilder);
            Color = subBuilder;
            break;
          }
          case 18: {
            global::Rv.Data.Graphics.Types.Gradient subBuilder = new global::Rv.Data.Graphics.Types.Gradient();
            if (fillCase_ == FillOneofCase.Gradient) {
              subBuilder.MergeFrom(Gradient);
            }
            input.ReadMessage(subBuilder);
            Gradient = subBuilder;
            break;
          }
          case 24: {
            IsEnabled = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
