// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: baseDocument.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from baseDocument.proto</summary>
  public static partial class BaseDocumentReflection {

    #region Descriptor
    /// <summary>File descriptor for baseDocument.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BaseDocumentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJiYXNlRG9jdW1lbnQucHJvdG8SB3J2LmRhdGEaD3dvcmtzcGFjZS5wcm90",
            "bxoQYmFzaWNUeXBlcy5wcm90byKeAQoIRG9jdW1lbnQSMgoQYXBwbGljYXRp",
            "b25faW5mbxgBIAEoCzIYLnJ2LmRhdGEuQXBwbGljYXRpb25JbmZvEhsKBHV1",
            "aWQYAiABKAsyDS5ydi5kYXRhLlVVSUQSGgoSdXNlc19yZWxhdGl2ZV91cmxz",
            "GAMgASgIEiUKCXdvcmtzcGFjZRgKIAEoCzISLnJ2LmRhdGEuV29ya3NwYWNl",
            "Io4BCglDYWNoZUluZm8SGwoEdXVpZBgBIAEoCzINLnJ2LmRhdGEuVVVJRBIt",
            "ChNhcHBsaWNhdGlvbl92ZXJzaW9uGAIgASgLMhAucnYuZGF0YS5WZXJzaW9u",
            "EhkKA3VybBgDIAEoCzIMLnJ2LmRhdGEuVVJMEhoKEmxhc3RfbW9kaWZpZWRf",
            "ZGF0ZRgEIAEoASLXBAoQUFZQRG9jdW1lbnRTdGF0ZRJBChBwcmltYXJ5X3Bs",
            "YXlsaXN0GAEgASgLMicucnYuZGF0YS5QVlBEb2N1bWVudFN0YXRlLlBsYXls",
            "aXN0U3RhdGUSQwoSYWx0ZXJuYXRlX3BsYXlsaXN0GAIgASgLMicucnYuZGF0",
            "YS5QVlBEb2N1bWVudFN0YXRlLlBsYXlsaXN0U3RhdGUSIgoacGxheWxpc3Rf",
            "c3BsaXRfaXNfdmVydGljYWwYAyABKAgSJQoOdGFyZ2V0ZWRfbGF5ZXIYBCAB",
            "KAsyDS5ydi5kYXRhLlVVSUQSJQoOc2VsZWN0ZWRfbGF5ZXIYBSABKAsyDS5y",
            "di5kYXRhLlVVSUQSIwoMbG9ja2VkX2xheWVyGAYgASgLMg0ucnYuZGF0YS5V",
            "VUlEEiEKGWxpdmVfdmlkZW9fcGxheWxpc3Rfc2NhbGUYByABKAESIwobc3Bs",
            "aXRfdmlld19kaXZpZGVyX3Bvc2l0aW9uGAggASgBGtsBCg1QbGF5bGlzdFN0",
            "YXRlEhsKBHV1aWQYAiABKAsyDS5ydi5kYXRhLlVVSUQSQgoGbGF5b3V0GAMg",
            "ASgOMjIucnYuZGF0YS5QVlBEb2N1bWVudFN0YXRlLlBsYXlsaXN0U3RhdGUu",
            "TGF5b3V0VHlwZRISCgppdGVtX3NjYWxlGAQgASgBIlUKCkxheW91dFR5cGUS",
            "EwoPTEFZT1VUX1RZUEVfQ1VFEAASFgoSTEFZT1VUX1RZUEVfQUNUSU9OEAES",
            "GgoWTEFZT1VUX1RZUEVfTElWRV9WSURFTxACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.WorkspaceReflection.Descriptor, global::Rv.Data.BasicTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.Document), global::Rv.Data.Document.Parser, new[]{ "ApplicationInfo", "Uuid", "UsesRelativeUrls", "Workspace" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.CacheInfo), global::Rv.Data.CacheInfo.Parser, new[]{ "Uuid", "ApplicationVersion", "Url", "LastModifiedDate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PVPDocumentState), global::Rv.Data.PVPDocumentState.Parser, new[]{ "PrimaryPlaylist", "AlternatePlaylist", "PlaylistSplitIsVertical", "TargetedLayer", "SelectedLayer", "LockedLayer", "LiveVideoPlaylistScale", "SplitViewDividerPosition" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PVPDocumentState.Types.PlaylistState), global::Rv.Data.PVPDocumentState.Types.PlaylistState.Parser, new[]{ "Uuid", "Layout", "ItemScale" }, null, new[]{ typeof(global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Document : pb::IMessage<Document>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Document> _parser = new pb::MessageParser<Document>(() => new Document());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Document> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.BaseDocumentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Document() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Document(Document other) : this() {
      applicationInfo_ = other.applicationInfo_ != null ? other.applicationInfo_.Clone() : null;
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      usesRelativeUrls_ = other.usesRelativeUrls_;
      workspace_ = other.workspace_ != null ? other.workspace_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Document Clone() {
      return new Document(this);
    }

    /// <summary>Field number for the "application_info" field.</summary>
    public const int ApplicationInfoFieldNumber = 1;
    private global::Rv.Data.ApplicationInfo applicationInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ApplicationInfo ApplicationInfo {
      get { return applicationInfo_; }
      set {
        applicationInfo_ = value;
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 2;
    private global::Rv.Data.UUID uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    /// <summary>Field number for the "uses_relative_urls" field.</summary>
    public const int UsesRelativeUrlsFieldNumber = 3;
    private bool usesRelativeUrls_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UsesRelativeUrls {
      get { return usesRelativeUrls_; }
      set {
        usesRelativeUrls_ = value;
      }
    }

    /// <summary>Field number for the "workspace" field.</summary>
    public const int WorkspaceFieldNumber = 10;
    private global::Rv.Data.Workspace workspace_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Workspace Workspace {
      get { return workspace_; }
      set {
        workspace_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Document);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Document other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ApplicationInfo, other.ApplicationInfo)) return false;
      if (!object.Equals(Uuid, other.Uuid)) return false;
      if (UsesRelativeUrls != other.UsesRelativeUrls) return false;
      if (!object.Equals(Workspace, other.Workspace)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (applicationInfo_ != null) hash ^= ApplicationInfo.GetHashCode();
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (UsesRelativeUrls != false) hash ^= UsesRelativeUrls.GetHashCode();
      if (workspace_ != null) hash ^= Workspace.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (applicationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ApplicationInfo);
      }
      if (uuid_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Uuid);
      }
      if (UsesRelativeUrls != false) {
        output.WriteRawTag(24);
        output.WriteBool(UsesRelativeUrls);
      }
      if (workspace_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Workspace);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (applicationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ApplicationInfo);
      }
      if (uuid_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Uuid);
      }
      if (UsesRelativeUrls != false) {
        output.WriteRawTag(24);
        output.WriteBool(UsesRelativeUrls);
      }
      if (workspace_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Workspace);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (applicationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApplicationInfo);
      }
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (UsesRelativeUrls != false) {
        size += 1 + 1;
      }
      if (workspace_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Workspace);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Document other) {
      if (other == null) {
        return;
      }
      if (other.applicationInfo_ != null) {
        if (applicationInfo_ == null) {
          ApplicationInfo = new global::Rv.Data.ApplicationInfo();
        }
        ApplicationInfo.MergeFrom(other.ApplicationInfo);
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::Rv.Data.UUID();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      if (other.UsesRelativeUrls != false) {
        UsesRelativeUrls = other.UsesRelativeUrls;
      }
      if (other.workspace_ != null) {
        if (workspace_ == null) {
          Workspace = new global::Rv.Data.Workspace();
        }
        Workspace.MergeFrom(other.Workspace);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (applicationInfo_ == null) {
              ApplicationInfo = new global::Rv.Data.ApplicationInfo();
            }
            input.ReadMessage(ApplicationInfo);
            break;
          }
          case 18: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 24: {
            UsesRelativeUrls = input.ReadBool();
            break;
          }
          case 82: {
            if (workspace_ == null) {
              Workspace = new global::Rv.Data.Workspace();
            }
            input.ReadMessage(Workspace);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (applicationInfo_ == null) {
              ApplicationInfo = new global::Rv.Data.ApplicationInfo();
            }
            input.ReadMessage(ApplicationInfo);
            break;
          }
          case 18: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 24: {
            UsesRelativeUrls = input.ReadBool();
            break;
          }
          case 82: {
            if (workspace_ == null) {
              Workspace = new global::Rv.Data.Workspace();
            }
            input.ReadMessage(Workspace);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CacheInfo : pb::IMessage<CacheInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CacheInfo> _parser = new pb::MessageParser<CacheInfo>(() => new CacheInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CacheInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.BaseDocumentReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CacheInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CacheInfo(CacheInfo other) : this() {
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      applicationVersion_ = other.applicationVersion_ != null ? other.applicationVersion_.Clone() : null;
      url_ = other.url_ != null ? other.url_.Clone() : null;
      lastModifiedDate_ = other.lastModifiedDate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CacheInfo Clone() {
      return new CacheInfo(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private global::Rv.Data.UUID uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    /// <summary>Field number for the "application_version" field.</summary>
    public const int ApplicationVersionFieldNumber = 2;
    private global::Rv.Data.Version applicationVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Version ApplicationVersion {
      get { return applicationVersion_; }
      set {
        applicationVersion_ = value;
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 3;
    private global::Rv.Data.URL url_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.URL Url {
      get { return url_; }
      set {
        url_ = value;
      }
    }

    /// <summary>Field number for the "last_modified_date" field.</summary>
    public const int LastModifiedDateFieldNumber = 4;
    private double lastModifiedDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LastModifiedDate {
      get { return lastModifiedDate_; }
      set {
        lastModifiedDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CacheInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CacheInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Uuid, other.Uuid)) return false;
      if (!object.Equals(ApplicationVersion, other.ApplicationVersion)) return false;
      if (!object.Equals(Url, other.Url)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastModifiedDate, other.LastModifiedDate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (applicationVersion_ != null) hash ^= ApplicationVersion.GetHashCode();
      if (url_ != null) hash ^= Url.GetHashCode();
      if (LastModifiedDate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastModifiedDate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (uuid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Uuid);
      }
      if (applicationVersion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ApplicationVersion);
      }
      if (url_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Url);
      }
      if (LastModifiedDate != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(LastModifiedDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (uuid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Uuid);
      }
      if (applicationVersion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ApplicationVersion);
      }
      if (url_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Url);
      }
      if (LastModifiedDate != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(LastModifiedDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (applicationVersion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApplicationVersion);
      }
      if (url_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Url);
      }
      if (LastModifiedDate != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CacheInfo other) {
      if (other == null) {
        return;
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::Rv.Data.UUID();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      if (other.applicationVersion_ != null) {
        if (applicationVersion_ == null) {
          ApplicationVersion = new global::Rv.Data.Version();
        }
        ApplicationVersion.MergeFrom(other.ApplicationVersion);
      }
      if (other.url_ != null) {
        if (url_ == null) {
          Url = new global::Rv.Data.URL();
        }
        Url.MergeFrom(other.Url);
      }
      if (other.LastModifiedDate != 0D) {
        LastModifiedDate = other.LastModifiedDate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 18: {
            if (applicationVersion_ == null) {
              ApplicationVersion = new global::Rv.Data.Version();
            }
            input.ReadMessage(ApplicationVersion);
            break;
          }
          case 26: {
            if (url_ == null) {
              Url = new global::Rv.Data.URL();
            }
            input.ReadMessage(Url);
            break;
          }
          case 33: {
            LastModifiedDate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 18: {
            if (applicationVersion_ == null) {
              ApplicationVersion = new global::Rv.Data.Version();
            }
            input.ReadMessage(ApplicationVersion);
            break;
          }
          case 26: {
            if (url_ == null) {
              Url = new global::Rv.Data.URL();
            }
            input.ReadMessage(Url);
            break;
          }
          case 33: {
            LastModifiedDate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PVPDocumentState : pb::IMessage<PVPDocumentState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PVPDocumentState> _parser = new pb::MessageParser<PVPDocumentState>(() => new PVPDocumentState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PVPDocumentState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.BaseDocumentReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PVPDocumentState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PVPDocumentState(PVPDocumentState other) : this() {
      primaryPlaylist_ = other.primaryPlaylist_ != null ? other.primaryPlaylist_.Clone() : null;
      alternatePlaylist_ = other.alternatePlaylist_ != null ? other.alternatePlaylist_.Clone() : null;
      playlistSplitIsVertical_ = other.playlistSplitIsVertical_;
      targetedLayer_ = other.targetedLayer_ != null ? other.targetedLayer_.Clone() : null;
      selectedLayer_ = other.selectedLayer_ != null ? other.selectedLayer_.Clone() : null;
      lockedLayer_ = other.lockedLayer_ != null ? other.lockedLayer_.Clone() : null;
      liveVideoPlaylistScale_ = other.liveVideoPlaylistScale_;
      splitViewDividerPosition_ = other.splitViewDividerPosition_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PVPDocumentState Clone() {
      return new PVPDocumentState(this);
    }

    /// <summary>Field number for the "primary_playlist" field.</summary>
    public const int PrimaryPlaylistFieldNumber = 1;
    private global::Rv.Data.PVPDocumentState.Types.PlaylistState primaryPlaylist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.PVPDocumentState.Types.PlaylistState PrimaryPlaylist {
      get { return primaryPlaylist_; }
      set {
        primaryPlaylist_ = value;
      }
    }

    /// <summary>Field number for the "alternate_playlist" field.</summary>
    public const int AlternatePlaylistFieldNumber = 2;
    private global::Rv.Data.PVPDocumentState.Types.PlaylistState alternatePlaylist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.PVPDocumentState.Types.PlaylistState AlternatePlaylist {
      get { return alternatePlaylist_; }
      set {
        alternatePlaylist_ = value;
      }
    }

    /// <summary>Field number for the "playlist_split_is_vertical" field.</summary>
    public const int PlaylistSplitIsVerticalFieldNumber = 3;
    private bool playlistSplitIsVertical_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaylistSplitIsVertical {
      get { return playlistSplitIsVertical_; }
      set {
        playlistSplitIsVertical_ = value;
      }
    }

    /// <summary>Field number for the "targeted_layer" field.</summary>
    public const int TargetedLayerFieldNumber = 4;
    private global::Rv.Data.UUID targetedLayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID TargetedLayer {
      get { return targetedLayer_; }
      set {
        targetedLayer_ = value;
      }
    }

    /// <summary>Field number for the "selected_layer" field.</summary>
    public const int SelectedLayerFieldNumber = 5;
    private global::Rv.Data.UUID selectedLayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID SelectedLayer {
      get { return selectedLayer_; }
      set {
        selectedLayer_ = value;
      }
    }

    /// <summary>Field number for the "locked_layer" field.</summary>
    public const int LockedLayerFieldNumber = 6;
    private global::Rv.Data.UUID lockedLayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID LockedLayer {
      get { return lockedLayer_; }
      set {
        lockedLayer_ = value;
      }
    }

    /// <summary>Field number for the "live_video_playlist_scale" field.</summary>
    public const int LiveVideoPlaylistScaleFieldNumber = 7;
    private double liveVideoPlaylistScale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LiveVideoPlaylistScale {
      get { return liveVideoPlaylistScale_; }
      set {
        liveVideoPlaylistScale_ = value;
      }
    }

    /// <summary>Field number for the "split_view_divider_position" field.</summary>
    public const int SplitViewDividerPositionFieldNumber = 8;
    private double splitViewDividerPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SplitViewDividerPosition {
      get { return splitViewDividerPosition_; }
      set {
        splitViewDividerPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PVPDocumentState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PVPDocumentState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PrimaryPlaylist, other.PrimaryPlaylist)) return false;
      if (!object.Equals(AlternatePlaylist, other.AlternatePlaylist)) return false;
      if (PlaylistSplitIsVertical != other.PlaylistSplitIsVertical) return false;
      if (!object.Equals(TargetedLayer, other.TargetedLayer)) return false;
      if (!object.Equals(SelectedLayer, other.SelectedLayer)) return false;
      if (!object.Equals(LockedLayer, other.LockedLayer)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LiveVideoPlaylistScale, other.LiveVideoPlaylistScale)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SplitViewDividerPosition, other.SplitViewDividerPosition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (primaryPlaylist_ != null) hash ^= PrimaryPlaylist.GetHashCode();
      if (alternatePlaylist_ != null) hash ^= AlternatePlaylist.GetHashCode();
      if (PlaylistSplitIsVertical != false) hash ^= PlaylistSplitIsVertical.GetHashCode();
      if (targetedLayer_ != null) hash ^= TargetedLayer.GetHashCode();
      if (selectedLayer_ != null) hash ^= SelectedLayer.GetHashCode();
      if (lockedLayer_ != null) hash ^= LockedLayer.GetHashCode();
      if (LiveVideoPlaylistScale != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LiveVideoPlaylistScale);
      if (SplitViewDividerPosition != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SplitViewDividerPosition);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (primaryPlaylist_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PrimaryPlaylist);
      }
      if (alternatePlaylist_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AlternatePlaylist);
      }
      if (PlaylistSplitIsVertical != false) {
        output.WriteRawTag(24);
        output.WriteBool(PlaylistSplitIsVertical);
      }
      if (targetedLayer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TargetedLayer);
      }
      if (selectedLayer_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SelectedLayer);
      }
      if (lockedLayer_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LockedLayer);
      }
      if (LiveVideoPlaylistScale != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(LiveVideoPlaylistScale);
      }
      if (SplitViewDividerPosition != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(SplitViewDividerPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (primaryPlaylist_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PrimaryPlaylist);
      }
      if (alternatePlaylist_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AlternatePlaylist);
      }
      if (PlaylistSplitIsVertical != false) {
        output.WriteRawTag(24);
        output.WriteBool(PlaylistSplitIsVertical);
      }
      if (targetedLayer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TargetedLayer);
      }
      if (selectedLayer_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SelectedLayer);
      }
      if (lockedLayer_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LockedLayer);
      }
      if (LiveVideoPlaylistScale != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(LiveVideoPlaylistScale);
      }
      if (SplitViewDividerPosition != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(SplitViewDividerPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (primaryPlaylist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrimaryPlaylist);
      }
      if (alternatePlaylist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AlternatePlaylist);
      }
      if (PlaylistSplitIsVertical != false) {
        size += 1 + 1;
      }
      if (targetedLayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetedLayer);
      }
      if (selectedLayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelectedLayer);
      }
      if (lockedLayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LockedLayer);
      }
      if (LiveVideoPlaylistScale != 0D) {
        size += 1 + 8;
      }
      if (SplitViewDividerPosition != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PVPDocumentState other) {
      if (other == null) {
        return;
      }
      if (other.primaryPlaylist_ != null) {
        if (primaryPlaylist_ == null) {
          PrimaryPlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
        }
        PrimaryPlaylist.MergeFrom(other.PrimaryPlaylist);
      }
      if (other.alternatePlaylist_ != null) {
        if (alternatePlaylist_ == null) {
          AlternatePlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
        }
        AlternatePlaylist.MergeFrom(other.AlternatePlaylist);
      }
      if (other.PlaylistSplitIsVertical != false) {
        PlaylistSplitIsVertical = other.PlaylistSplitIsVertical;
      }
      if (other.targetedLayer_ != null) {
        if (targetedLayer_ == null) {
          TargetedLayer = new global::Rv.Data.UUID();
        }
        TargetedLayer.MergeFrom(other.TargetedLayer);
      }
      if (other.selectedLayer_ != null) {
        if (selectedLayer_ == null) {
          SelectedLayer = new global::Rv.Data.UUID();
        }
        SelectedLayer.MergeFrom(other.SelectedLayer);
      }
      if (other.lockedLayer_ != null) {
        if (lockedLayer_ == null) {
          LockedLayer = new global::Rv.Data.UUID();
        }
        LockedLayer.MergeFrom(other.LockedLayer);
      }
      if (other.LiveVideoPlaylistScale != 0D) {
        LiveVideoPlaylistScale = other.LiveVideoPlaylistScale;
      }
      if (other.SplitViewDividerPosition != 0D) {
        SplitViewDividerPosition = other.SplitViewDividerPosition;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (primaryPlaylist_ == null) {
              PrimaryPlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
            }
            input.ReadMessage(PrimaryPlaylist);
            break;
          }
          case 18: {
            if (alternatePlaylist_ == null) {
              AlternatePlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
            }
            input.ReadMessage(AlternatePlaylist);
            break;
          }
          case 24: {
            PlaylistSplitIsVertical = input.ReadBool();
            break;
          }
          case 34: {
            if (targetedLayer_ == null) {
              TargetedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(TargetedLayer);
            break;
          }
          case 42: {
            if (selectedLayer_ == null) {
              SelectedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(SelectedLayer);
            break;
          }
          case 50: {
            if (lockedLayer_ == null) {
              LockedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(LockedLayer);
            break;
          }
          case 57: {
            LiveVideoPlaylistScale = input.ReadDouble();
            break;
          }
          case 65: {
            SplitViewDividerPosition = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (primaryPlaylist_ == null) {
              PrimaryPlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
            }
            input.ReadMessage(PrimaryPlaylist);
            break;
          }
          case 18: {
            if (alternatePlaylist_ == null) {
              AlternatePlaylist = new global::Rv.Data.PVPDocumentState.Types.PlaylistState();
            }
            input.ReadMessage(AlternatePlaylist);
            break;
          }
          case 24: {
            PlaylistSplitIsVertical = input.ReadBool();
            break;
          }
          case 34: {
            if (targetedLayer_ == null) {
              TargetedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(TargetedLayer);
            break;
          }
          case 42: {
            if (selectedLayer_ == null) {
              SelectedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(SelectedLayer);
            break;
          }
          case 50: {
            if (lockedLayer_ == null) {
              LockedLayer = new global::Rv.Data.UUID();
            }
            input.ReadMessage(LockedLayer);
            break;
          }
          case 57: {
            LiveVideoPlaylistScale = input.ReadDouble();
            break;
          }
          case 65: {
            SplitViewDividerPosition = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PVPDocumentState message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class PlaylistState : pb::IMessage<PlaylistState>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PlaylistState> _parser = new pb::MessageParser<PlaylistState>(() => new PlaylistState());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PlaylistState> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.PVPDocumentState.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlaylistState() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlaylistState(PlaylistState other) : this() {
          uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
          layout_ = other.layout_;
          itemScale_ = other.itemScale_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PlaylistState Clone() {
          return new PlaylistState(this);
        }

        /// <summary>Field number for the "uuid" field.</summary>
        public const int UuidFieldNumber = 2;
        private global::Rv.Data.UUID uuid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.UUID Uuid {
          get { return uuid_; }
          set {
            uuid_ = value;
          }
        }

        /// <summary>Field number for the "layout" field.</summary>
        public const int LayoutFieldNumber = 3;
        private global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType layout_ = global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType Layout {
          get { return layout_; }
          set {
            layout_ = value;
          }
        }

        /// <summary>Field number for the "item_scale" field.</summary>
        public const int ItemScaleFieldNumber = 4;
        private double itemScale_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double ItemScale {
          get { return itemScale_; }
          set {
            itemScale_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as PlaylistState);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PlaylistState other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Uuid, other.Uuid)) return false;
          if (Layout != other.Layout) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ItemScale, other.ItemScale)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (uuid_ != null) hash ^= Uuid.GetHashCode();
          if (Layout != global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue) hash ^= Layout.GetHashCode();
          if (ItemScale != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ItemScale);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (uuid_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Uuid);
          }
          if (Layout != global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Layout);
          }
          if (ItemScale != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(ItemScale);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (uuid_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Uuid);
          }
          if (Layout != global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Layout);
          }
          if (ItemScale != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(ItemScale);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (uuid_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
          }
          if (Layout != global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Layout);
          }
          if (ItemScale != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PlaylistState other) {
          if (other == null) {
            return;
          }
          if (other.uuid_ != null) {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            Uuid.MergeFrom(other.Uuid);
          }
          if (other.Layout != global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType.Cue) {
            Layout = other.Layout;
          }
          if (other.ItemScale != 0D) {
            ItemScale = other.ItemScale;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                if (uuid_ == null) {
                  Uuid = new global::Rv.Data.UUID();
                }
                input.ReadMessage(Uuid);
                break;
              }
              case 24: {
                Layout = (global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType) input.ReadEnum();
                break;
              }
              case 33: {
                ItemScale = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                if (uuid_ == null) {
                  Uuid = new global::Rv.Data.UUID();
                }
                input.ReadMessage(Uuid);
                break;
              }
              case 24: {
                Layout = (global::Rv.Data.PVPDocumentState.Types.PlaylistState.Types.LayoutType) input.ReadEnum();
                break;
              }
              case 33: {
                ItemScale = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the PlaylistState message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum LayoutType {
            [pbr::OriginalName("LAYOUT_TYPE_CUE")] Cue = 0,
            [pbr::OriginalName("LAYOUT_TYPE_ACTION")] Action = 1,
            [pbr::OriginalName("LAYOUT_TYPE_LIVE_VIDEO")] LiveVideo = 2,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
