// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: propSlide.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from propSlide.proto</summary>
  public static partial class PropSlideReflection {

    #region Descriptor
    /// <summary>File descriptor for propSlide.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PropSlideReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm9wU2xpZGUucHJvdG8SB3J2LmRhdGEaC3NsaWRlLnByb3RvGg1lZmZl",
            "Y3RzLnByb3RvIlgKCVByb3BTbGlkZRIiCgpiYXNlX3NsaWRlGAEgASgLMg4u",
            "cnYuZGF0YS5TbGlkZRInCgp0cmFuc2l0aW9uGAIgASgLMhMucnYuZGF0YS5U",
            "cmFuc2l0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.SlideReflection.Descriptor, global::Rv.Data.EffectsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PropSlide), global::Rv.Data.PropSlide.Parser, new[]{ "BaseSlide", "Transition" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PropSlide : pb::IMessage<PropSlide>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PropSlide> _parser = new pb::MessageParser<PropSlide>(() => new PropSlide());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PropSlide> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.PropSlideReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropSlide() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropSlide(PropSlide other) : this() {
      baseSlide_ = other.baseSlide_ != null ? other.baseSlide_.Clone() : null;
      transition_ = other.transition_ != null ? other.transition_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropSlide Clone() {
      return new PropSlide(this);
    }

    /// <summary>Field number for the "base_slide" field.</summary>
    public const int BaseSlideFieldNumber = 1;
    private global::Rv.Data.Slide baseSlide_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Slide BaseSlide {
      get { return baseSlide_; }
      set {
        baseSlide_ = value;
      }
    }

    /// <summary>Field number for the "transition" field.</summary>
    public const int TransitionFieldNumber = 2;
    private global::Rv.Data.Transition transition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Transition Transition {
      get { return transition_; }
      set {
        transition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PropSlide);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PropSlide other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseSlide, other.BaseSlide)) return false;
      if (!object.Equals(Transition, other.Transition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseSlide_ != null) hash ^= BaseSlide.GetHashCode();
      if (transition_ != null) hash ^= Transition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseSlide_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSlide);
      }
      if (transition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseSlide_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseSlide);
      }
      if (transition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseSlide_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseSlide);
      }
      if (transition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PropSlide other) {
      if (other == null) {
        return;
      }
      if (other.baseSlide_ != null) {
        if (baseSlide_ == null) {
          BaseSlide = new global::Rv.Data.Slide();
        }
        BaseSlide.MergeFrom(other.BaseSlide);
      }
      if (other.transition_ != null) {
        if (transition_ == null) {
          Transition = new global::Rv.Data.Transition();
        }
        Transition.MergeFrom(other.Transition);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseSlide_ == null) {
              BaseSlide = new global::Rv.Data.Slide();
            }
            input.ReadMessage(BaseSlide);
            break;
          }
          case 18: {
            if (transition_ == null) {
              Transition = new global::Rv.Data.Transition();
            }
            input.ReadMessage(Transition);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseSlide_ == null) {
              BaseSlide = new global::Rv.Data.Slide();
            }
            input.ReadMessage(BaseSlide);
            break;
          }
          case 18: {
            if (transition_ == null) {
              Transition = new global::Rv.Data.Transition();
            }
            input.ReadMessage(Transition);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
