// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: propresenter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from propresenter.proto</summary>
  public static partial class PropresenterReflection {

    #region Descriptor
    /// <summary>File descriptor for propresenter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PropresenterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwcm9wcmVzZW50ZXIucHJvdG8SB3J2LmRhdGEaEGJhc2ljVHlwZXMucHJv",
            "dG8aDnBsYXlsaXN0LnByb3RvGgxhY3Rpb24ucHJvdG8i7wIKEFBsYXlsaXN0",
            "RG9jdW1lbnQSMgoQYXBwbGljYXRpb25faW5mbxgBIAEoCzIYLnJ2LmRhdGEu",
            "QXBwbGljYXRpb25JbmZvEiwKBHR5cGUYAiABKA4yHi5ydi5kYXRhLlBsYXls",
            "aXN0RG9jdW1lbnQuVHlwZRIkCglyb290X25vZGUYAyABKAsyES5ydi5kYXRh",
            "LlBsYXlsaXN0EiMKBHRhZ3MYBCADKAsyFS5ydi5kYXRhLlBsYXlsaXN0LlRh",
            "ZxIuChNsaXZlX3ZpZGVvX3BsYXlsaXN0GAUgASgLMhEucnYuZGF0YS5QbGF5",
            "bGlzdBItChJkb3dubG9hZHNfcGxheWxpc3QYBiABKAsyES5ydi5kYXRhLlBs",
            "YXlsaXN0Ik8KBFR5cGUSEAoMVFlQRV9VTktOT1dOEAASFQoRVFlQRV9QUkVT",
            "RU5UQVRJT04QARIOCgpUWVBFX01FRElBEAISDgoKVFlQRV9BVURJTxADIjkK",
            "EFNldHRpbmdzRG9jdW1lbnQSJQoGbGFiZWxzGAIgAygLMhUucnYuZGF0YS5B",
            "Y3Rpb24uTGFiZWxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.BasicTypesReflection.Descriptor, global::Rv.Data.PlaylistReflection.Descriptor, global::Rv.Data.ActionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.PlaylistDocument), global::Rv.Data.PlaylistDocument.Parser, new[]{ "ApplicationInfo", "Type", "RootNode", "Tags", "LiveVideoPlaylist", "DownloadsPlaylist" }, null, new[]{ typeof(global::Rv.Data.PlaylistDocument.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.SettingsDocument), global::Rv.Data.SettingsDocument.Parser, new[]{ "Labels" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlaylistDocument : pb::IMessage<PlaylistDocument>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlaylistDocument> _parser = new pb::MessageParser<PlaylistDocument>(() => new PlaylistDocument());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlaylistDocument> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.PropresenterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaylistDocument() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaylistDocument(PlaylistDocument other) : this() {
      applicationInfo_ = other.applicationInfo_ != null ? other.applicationInfo_.Clone() : null;
      type_ = other.type_;
      rootNode_ = other.rootNode_ != null ? other.rootNode_.Clone() : null;
      tags_ = other.tags_.Clone();
      liveVideoPlaylist_ = other.liveVideoPlaylist_ != null ? other.liveVideoPlaylist_.Clone() : null;
      downloadsPlaylist_ = other.downloadsPlaylist_ != null ? other.downloadsPlaylist_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaylistDocument Clone() {
      return new PlaylistDocument(this);
    }

    /// <summary>Field number for the "application_info" field.</summary>
    public const int ApplicationInfoFieldNumber = 1;
    private global::Rv.Data.ApplicationInfo applicationInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ApplicationInfo ApplicationInfo {
      get { return applicationInfo_; }
      set {
        applicationInfo_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Rv.Data.PlaylistDocument.Types.Type type_ = global::Rv.Data.PlaylistDocument.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.PlaylistDocument.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "root_node" field.</summary>
    public const int RootNodeFieldNumber = 3;
    private global::Rv.Data.Playlist rootNode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Playlist RootNode {
      get { return rootNode_; }
      set {
        rootNode_ = value;
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Rv.Data.Playlist.Types.Tag> _repeated_tags_codec
        = pb::FieldCodec.ForMessage(34, global::Rv.Data.Playlist.Types.Tag.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Playlist.Types.Tag> tags_ = new pbc::RepeatedField<global::Rv.Data.Playlist.Types.Tag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Playlist.Types.Tag> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "live_video_playlist" field.</summary>
    public const int LiveVideoPlaylistFieldNumber = 5;
    private global::Rv.Data.Playlist liveVideoPlaylist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Playlist LiveVideoPlaylist {
      get { return liveVideoPlaylist_; }
      set {
        liveVideoPlaylist_ = value;
      }
    }

    /// <summary>Field number for the "downloads_playlist" field.</summary>
    public const int DownloadsPlaylistFieldNumber = 6;
    private global::Rv.Data.Playlist downloadsPlaylist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Playlist DownloadsPlaylist {
      get { return downloadsPlaylist_; }
      set {
        downloadsPlaylist_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlaylistDocument);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlaylistDocument other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ApplicationInfo, other.ApplicationInfo)) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(RootNode, other.RootNode)) return false;
      if(!tags_.Equals(other.tags_)) return false;
      if (!object.Equals(LiveVideoPlaylist, other.LiveVideoPlaylist)) return false;
      if (!object.Equals(DownloadsPlaylist, other.DownloadsPlaylist)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (applicationInfo_ != null) hash ^= ApplicationInfo.GetHashCode();
      if (Type != global::Rv.Data.PlaylistDocument.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (rootNode_ != null) hash ^= RootNode.GetHashCode();
      hash ^= tags_.GetHashCode();
      if (liveVideoPlaylist_ != null) hash ^= LiveVideoPlaylist.GetHashCode();
      if (downloadsPlaylist_ != null) hash ^= DownloadsPlaylist.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (applicationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ApplicationInfo);
      }
      if (Type != global::Rv.Data.PlaylistDocument.Types.Type.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (rootNode_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RootNode);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      if (liveVideoPlaylist_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LiveVideoPlaylist);
      }
      if (downloadsPlaylist_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DownloadsPlaylist);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (applicationInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ApplicationInfo);
      }
      if (Type != global::Rv.Data.PlaylistDocument.Types.Type.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (rootNode_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RootNode);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (liveVideoPlaylist_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LiveVideoPlaylist);
      }
      if (downloadsPlaylist_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DownloadsPlaylist);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (applicationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApplicationInfo);
      }
      if (Type != global::Rv.Data.PlaylistDocument.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (rootNode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RootNode);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (liveVideoPlaylist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LiveVideoPlaylist);
      }
      if (downloadsPlaylist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DownloadsPlaylist);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlaylistDocument other) {
      if (other == null) {
        return;
      }
      if (other.applicationInfo_ != null) {
        if (applicationInfo_ == null) {
          ApplicationInfo = new global::Rv.Data.ApplicationInfo();
        }
        ApplicationInfo.MergeFrom(other.ApplicationInfo);
      }
      if (other.Type != global::Rv.Data.PlaylistDocument.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.rootNode_ != null) {
        if (rootNode_ == null) {
          RootNode = new global::Rv.Data.Playlist();
        }
        RootNode.MergeFrom(other.RootNode);
      }
      tags_.Add(other.tags_);
      if (other.liveVideoPlaylist_ != null) {
        if (liveVideoPlaylist_ == null) {
          LiveVideoPlaylist = new global::Rv.Data.Playlist();
        }
        LiveVideoPlaylist.MergeFrom(other.LiveVideoPlaylist);
      }
      if (other.downloadsPlaylist_ != null) {
        if (downloadsPlaylist_ == null) {
          DownloadsPlaylist = new global::Rv.Data.Playlist();
        }
        DownloadsPlaylist.MergeFrom(other.DownloadsPlaylist);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (applicationInfo_ == null) {
              ApplicationInfo = new global::Rv.Data.ApplicationInfo();
            }
            input.ReadMessage(ApplicationInfo);
            break;
          }
          case 16: {
            Type = (global::Rv.Data.PlaylistDocument.Types.Type) input.ReadEnum();
            break;
          }
          case 26: {
            if (rootNode_ == null) {
              RootNode = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(RootNode);
            break;
          }
          case 34: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 42: {
            if (liveVideoPlaylist_ == null) {
              LiveVideoPlaylist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(LiveVideoPlaylist);
            break;
          }
          case 50: {
            if (downloadsPlaylist_ == null) {
              DownloadsPlaylist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(DownloadsPlaylist);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (applicationInfo_ == null) {
              ApplicationInfo = new global::Rv.Data.ApplicationInfo();
            }
            input.ReadMessage(ApplicationInfo);
            break;
          }
          case 16: {
            Type = (global::Rv.Data.PlaylistDocument.Types.Type) input.ReadEnum();
            break;
          }
          case 26: {
            if (rootNode_ == null) {
              RootNode = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(RootNode);
            break;
          }
          case 34: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 42: {
            if (liveVideoPlaylist_ == null) {
              LiveVideoPlaylist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(LiveVideoPlaylist);
            break;
          }
          case 50: {
            if (downloadsPlaylist_ == null) {
              DownloadsPlaylist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(DownloadsPlaylist);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PlaylistDocument message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("TYPE_UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("TYPE_PRESENTATION")] Presentation = 1,
        [pbr::OriginalName("TYPE_MEDIA")] Media = 2,
        [pbr::OriginalName("TYPE_AUDIO")] Audio = 3,
      }

    }
    #endregion

  }

  public sealed partial class SettingsDocument : pb::IMessage<SettingsDocument>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SettingsDocument> _parser = new pb::MessageParser<SettingsDocument>(() => new SettingsDocument());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SettingsDocument> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.PropresenterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettingsDocument() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettingsDocument(SettingsDocument other) : this() {
      labels_ = other.labels_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettingsDocument Clone() {
      return new SettingsDocument(this);
    }

    /// <summary>Field number for the "labels" field.</summary>
    public const int LabelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Rv.Data.Action.Types.Label> _repeated_labels_codec
        = pb::FieldCodec.ForMessage(18, global::Rv.Data.Action.Types.Label.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Action.Types.Label> labels_ = new pbc::RepeatedField<global::Rv.Data.Action.Types.Label>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Action.Types.Label> Labels {
      get { return labels_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SettingsDocument);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SettingsDocument other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!labels_.Equals(other.labels_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= labels_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      labels_.WriteTo(output, _repeated_labels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      labels_.WriteTo(ref output, _repeated_labels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += labels_.CalculateSize(_repeated_labels_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SettingsDocument other) {
      if (other == null) {
        return;
      }
      labels_.Add(other.labels_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            labels_.AddEntriesFrom(input, _repeated_labels_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            labels_.AddEntriesFrom(ref input, _repeated_labels_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
