// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proscreen.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from proscreen.proto</summary>
  public static partial class ProscreenReflection {

    #region Descriptor
    /// <summary>File descriptor for proscreen.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProscreenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm9zY3JlZW4ucHJvdG8SB3J2LmRhdGEaDXNjcmVlbnMucHJvdG8aEGJh",
            "c2ljVHlwZXMucHJvdG8iqQYKElByb1ByZXNlbnRlclNjcmVlbhIMCgRuYW1l",
            "GAEgASgJEjsKC3NjcmVlbl90eXBlGAIgASgOMiYucnYuZGF0YS5Qcm9QcmVz",
            "ZW50ZXJTY3JlZW4uU2NyZWVuVHlwZRIoChBiYWNrZ3JvdW5kX2NvbG9yGAYg",
            "ASgLMg4ucnYuZGF0YS5Db2xvchIbCgR1dWlkGAcgASgLMg0ucnYuZGF0YS5V",
            "VUlEEiAKGGJhY2tncm91bmRfY29sb3JfZW5hYmxlZBgIIAEoCBJLChJhcnJh",
            "bmdlbWVudF9zaW5nbGUYAyABKAsyLS5ydi5kYXRhLlByb1ByZXNlbnRlclNj",
            "cmVlbi5TaW5nbGVBcnJhbmdlbWVudEgAEk8KFGFycmFuZ2VtZW50X2NvbWJp",
            "bmVkGAQgASgLMi8ucnYuZGF0YS5Qcm9QcmVzZW50ZXJTY3JlZW4uQ29tYmlu",
            "ZWRBcnJhbmdlbWVudEgAElIKFmFycmFuZ2VtZW50X2VkZ2VfYmxlbmQYBSAB",
            "KAsyMC5ydi5kYXRhLlByb1ByZXNlbnRlclNjcmVlbi5FZGdlQmxlbmRBcnJh",
            "bmdlbWVudEgAGjUKEVNpbmdsZUFycmFuZ2VtZW50EiAKB3NjcmVlbnMYASAD",
            "KAsyDy5ydi5kYXRhLlNjcmVlbhpWChNDb21iaW5lZEFycmFuZ2VtZW50EiAK",
            "B3NjcmVlbnMYASADKAsyDy5ydi5kYXRhLlNjcmVlbhIMCgRyb3dzGAIgASgN",
            "Eg8KB2NvbHVtbnMYAyABKA0adwoURWRnZUJsZW5kQXJyYW5nZW1lbnQSFAoM",
            "c2NyZWVuX2NvdW50GAEgASgNEiAKB3NjcmVlbnMYAiADKAsyDy5ydi5kYXRh",
            "LlNjcmVlbhInCgtlZGdlX2JsZW5kcxgDIAMoCzISLnJ2LmRhdGEuRWRnZUJs",
            "ZW5kIlYKClNjcmVlblR5cGUSFwoTU0NSRUVOX1RZUEVfVU5LTk9XThAAEhgK",
            "FFNDUkVFTl9UWVBFX0FVRElFTkNFEAESFQoRU0NSRUVOX1RZUEVfU1RBR0UQ",
            "AkINCgtBcnJhbmdlbWVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.ScreensReflection.Descriptor, global::Rv.Data.BasicTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.ProPresenterScreen), global::Rv.Data.ProPresenterScreen.Parser, new[]{ "Name", "ScreenType", "BackgroundColor", "Uuid", "BackgroundColorEnabled", "ArrangementSingle", "ArrangementCombined", "ArrangementEdgeBlend" }, new[]{ "Arrangement" }, new[]{ typeof(global::Rv.Data.ProPresenterScreen.Types.ScreenType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.ProPresenterScreen.Types.SingleArrangement), global::Rv.Data.ProPresenterScreen.Types.SingleArrangement.Parser, new[]{ "Screens" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement), global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement.Parser, new[]{ "Screens", "Rows", "Columns" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement), global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement.Parser, new[]{ "ScreenCount", "Screens", "EdgeBlends" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProPresenterScreen : pb::IMessage<ProPresenterScreen>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProPresenterScreen> _parser = new pb::MessageParser<ProPresenterScreen>(() => new ProPresenterScreen());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProPresenterScreen> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.ProscreenReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProPresenterScreen() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProPresenterScreen(ProPresenterScreen other) : this() {
      name_ = other.name_;
      screenType_ = other.screenType_;
      backgroundColor_ = other.backgroundColor_ != null ? other.backgroundColor_.Clone() : null;
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      backgroundColorEnabled_ = other.backgroundColorEnabled_;
      switch (other.ArrangementCase) {
        case ArrangementOneofCase.ArrangementSingle:
          ArrangementSingle = other.ArrangementSingle.Clone();
          break;
        case ArrangementOneofCase.ArrangementCombined:
          ArrangementCombined = other.ArrangementCombined.Clone();
          break;
        case ArrangementOneofCase.ArrangementEdgeBlend:
          ArrangementEdgeBlend = other.ArrangementEdgeBlend.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProPresenterScreen Clone() {
      return new ProPresenterScreen(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "screen_type" field.</summary>
    public const int ScreenTypeFieldNumber = 2;
    private global::Rv.Data.ProPresenterScreen.Types.ScreenType screenType_ = global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ProPresenterScreen.Types.ScreenType ScreenType {
      get { return screenType_; }
      set {
        screenType_ = value;
      }
    }

    /// <summary>Field number for the "background_color" field.</summary>
    public const int BackgroundColorFieldNumber = 6;
    private global::Rv.Data.Color backgroundColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Color BackgroundColor {
      get { return backgroundColor_; }
      set {
        backgroundColor_ = value;
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 7;
    private global::Rv.Data.UUID uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    /// <summary>Field number for the "background_color_enabled" field.</summary>
    public const int BackgroundColorEnabledFieldNumber = 8;
    private bool backgroundColorEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BackgroundColorEnabled {
      get { return backgroundColorEnabled_; }
      set {
        backgroundColorEnabled_ = value;
      }
    }

    /// <summary>Field number for the "arrangement_single" field.</summary>
    public const int ArrangementSingleFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ProPresenterScreen.Types.SingleArrangement ArrangementSingle {
      get { return arrangementCase_ == ArrangementOneofCase.ArrangementSingle ? (global::Rv.Data.ProPresenterScreen.Types.SingleArrangement) arrangement_ : null; }
      set {
        arrangement_ = value;
        arrangementCase_ = value == null ? ArrangementOneofCase.None : ArrangementOneofCase.ArrangementSingle;
      }
    }

    /// <summary>Field number for the "arrangement_combined" field.</summary>
    public const int ArrangementCombinedFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement ArrangementCombined {
      get { return arrangementCase_ == ArrangementOneofCase.ArrangementCombined ? (global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement) arrangement_ : null; }
      set {
        arrangement_ = value;
        arrangementCase_ = value == null ? ArrangementOneofCase.None : ArrangementOneofCase.ArrangementCombined;
      }
    }

    /// <summary>Field number for the "arrangement_edge_blend" field.</summary>
    public const int ArrangementEdgeBlendFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement ArrangementEdgeBlend {
      get { return arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend ? (global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement) arrangement_ : null; }
      set {
        arrangement_ = value;
        arrangementCase_ = value == null ? ArrangementOneofCase.None : ArrangementOneofCase.ArrangementEdgeBlend;
      }
    }

    private object arrangement_;
    /// <summary>Enum of possible cases for the "Arrangement" oneof.</summary>
    public enum ArrangementOneofCase {
      None = 0,
      ArrangementSingle = 3,
      ArrangementCombined = 4,
      ArrangementEdgeBlend = 5,
    }
    private ArrangementOneofCase arrangementCase_ = ArrangementOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArrangementOneofCase ArrangementCase {
      get { return arrangementCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearArrangement() {
      arrangementCase_ = ArrangementOneofCase.None;
      arrangement_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProPresenterScreen);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProPresenterScreen other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (ScreenType != other.ScreenType) return false;
      if (!object.Equals(BackgroundColor, other.BackgroundColor)) return false;
      if (!object.Equals(Uuid, other.Uuid)) return false;
      if (BackgroundColorEnabled != other.BackgroundColorEnabled) return false;
      if (!object.Equals(ArrangementSingle, other.ArrangementSingle)) return false;
      if (!object.Equals(ArrangementCombined, other.ArrangementCombined)) return false;
      if (!object.Equals(ArrangementEdgeBlend, other.ArrangementEdgeBlend)) return false;
      if (ArrangementCase != other.ArrangementCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ScreenType != global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown) hash ^= ScreenType.GetHashCode();
      if (backgroundColor_ != null) hash ^= BackgroundColor.GetHashCode();
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (BackgroundColorEnabled != false) hash ^= BackgroundColorEnabled.GetHashCode();
      if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) hash ^= ArrangementSingle.GetHashCode();
      if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) hash ^= ArrangementCombined.GetHashCode();
      if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) hash ^= ArrangementEdgeBlend.GetHashCode();
      hash ^= (int) arrangementCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ScreenType != global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ScreenType);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) {
        output.WriteRawTag(26);
        output.WriteMessage(ArrangementSingle);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) {
        output.WriteRawTag(34);
        output.WriteMessage(ArrangementCombined);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) {
        output.WriteRawTag(42);
        output.WriteMessage(ArrangementEdgeBlend);
      }
      if (backgroundColor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BackgroundColor);
      }
      if (uuid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Uuid);
      }
      if (BackgroundColorEnabled != false) {
        output.WriteRawTag(64);
        output.WriteBool(BackgroundColorEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ScreenType != global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ScreenType);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) {
        output.WriteRawTag(26);
        output.WriteMessage(ArrangementSingle);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) {
        output.WriteRawTag(34);
        output.WriteMessage(ArrangementCombined);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) {
        output.WriteRawTag(42);
        output.WriteMessage(ArrangementEdgeBlend);
      }
      if (backgroundColor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BackgroundColor);
      }
      if (uuid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Uuid);
      }
      if (BackgroundColorEnabled != false) {
        output.WriteRawTag(64);
        output.WriteBool(BackgroundColorEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ScreenType != global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ScreenType);
      }
      if (backgroundColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BackgroundColor);
      }
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (BackgroundColorEnabled != false) {
        size += 1 + 1;
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArrangementSingle);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArrangementCombined);
      }
      if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArrangementEdgeBlend);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProPresenterScreen other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ScreenType != global::Rv.Data.ProPresenterScreen.Types.ScreenType.Unknown) {
        ScreenType = other.ScreenType;
      }
      if (other.backgroundColor_ != null) {
        if (backgroundColor_ == null) {
          BackgroundColor = new global::Rv.Data.Color();
        }
        BackgroundColor.MergeFrom(other.BackgroundColor);
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::Rv.Data.UUID();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      if (other.BackgroundColorEnabled != false) {
        BackgroundColorEnabled = other.BackgroundColorEnabled;
      }
      switch (other.ArrangementCase) {
        case ArrangementOneofCase.ArrangementSingle:
          if (ArrangementSingle == null) {
            ArrangementSingle = new global::Rv.Data.ProPresenterScreen.Types.SingleArrangement();
          }
          ArrangementSingle.MergeFrom(other.ArrangementSingle);
          break;
        case ArrangementOneofCase.ArrangementCombined:
          if (ArrangementCombined == null) {
            ArrangementCombined = new global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement();
          }
          ArrangementCombined.MergeFrom(other.ArrangementCombined);
          break;
        case ArrangementOneofCase.ArrangementEdgeBlend:
          if (ArrangementEdgeBlend == null) {
            ArrangementEdgeBlend = new global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement();
          }
          ArrangementEdgeBlend.MergeFrom(other.ArrangementEdgeBlend);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            ScreenType = (global::Rv.Data.ProPresenterScreen.Types.ScreenType) input.ReadEnum();
            break;
          }
          case 26: {
            global::Rv.Data.ProPresenterScreen.Types.SingleArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.SingleArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) {
              subBuilder.MergeFrom(ArrangementSingle);
            }
            input.ReadMessage(subBuilder);
            ArrangementSingle = subBuilder;
            break;
          }
          case 34: {
            global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) {
              subBuilder.MergeFrom(ArrangementCombined);
            }
            input.ReadMessage(subBuilder);
            ArrangementCombined = subBuilder;
            break;
          }
          case 42: {
            global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) {
              subBuilder.MergeFrom(ArrangementEdgeBlend);
            }
            input.ReadMessage(subBuilder);
            ArrangementEdgeBlend = subBuilder;
            break;
          }
          case 50: {
            if (backgroundColor_ == null) {
              BackgroundColor = new global::Rv.Data.Color();
            }
            input.ReadMessage(BackgroundColor);
            break;
          }
          case 58: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 64: {
            BackgroundColorEnabled = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            ScreenType = (global::Rv.Data.ProPresenterScreen.Types.ScreenType) input.ReadEnum();
            break;
          }
          case 26: {
            global::Rv.Data.ProPresenterScreen.Types.SingleArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.SingleArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementSingle) {
              subBuilder.MergeFrom(ArrangementSingle);
            }
            input.ReadMessage(subBuilder);
            ArrangementSingle = subBuilder;
            break;
          }
          case 34: {
            global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.CombinedArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementCombined) {
              subBuilder.MergeFrom(ArrangementCombined);
            }
            input.ReadMessage(subBuilder);
            ArrangementCombined = subBuilder;
            break;
          }
          case 42: {
            global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement subBuilder = new global::Rv.Data.ProPresenterScreen.Types.EdgeBlendArrangement();
            if (arrangementCase_ == ArrangementOneofCase.ArrangementEdgeBlend) {
              subBuilder.MergeFrom(ArrangementEdgeBlend);
            }
            input.ReadMessage(subBuilder);
            ArrangementEdgeBlend = subBuilder;
            break;
          }
          case 50: {
            if (backgroundColor_ == null) {
              BackgroundColor = new global::Rv.Data.Color();
            }
            input.ReadMessage(BackgroundColor);
            break;
          }
          case 58: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 64: {
            BackgroundColorEnabled = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ProPresenterScreen message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ScreenType {
        [pbr::OriginalName("SCREEN_TYPE_UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SCREEN_TYPE_AUDIENCE")] Audience = 1,
        [pbr::OriginalName("SCREEN_TYPE_STAGE")] Stage = 2,
      }

      public sealed partial class SingleArrangement : pb::IMessage<SingleArrangement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SingleArrangement> _parser = new pb::MessageParser<SingleArrangement>(() => new SingleArrangement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SingleArrangement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.ProPresenterScreen.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SingleArrangement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SingleArrangement(SingleArrangement other) : this() {
          screens_ = other.screens_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SingleArrangement Clone() {
          return new SingleArrangement(this);
        }

        /// <summary>Field number for the "screens" field.</summary>
        public const int ScreensFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Rv.Data.Screen> _repeated_screens_codec
            = pb::FieldCodec.ForMessage(10, global::Rv.Data.Screen.Parser);
        private readonly pbc::RepeatedField<global::Rv.Data.Screen> screens_ = new pbc::RepeatedField<global::Rv.Data.Screen>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Rv.Data.Screen> Screens {
          get { return screens_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SingleArrangement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SingleArrangement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!screens_.Equals(other.screens_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= screens_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          screens_.WriteTo(output, _repeated_screens_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          screens_.WriteTo(ref output, _repeated_screens_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += screens_.CalculateSize(_repeated_screens_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SingleArrangement other) {
          if (other == null) {
            return;
          }
          screens_.Add(other.screens_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                screens_.AddEntriesFrom(input, _repeated_screens_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                screens_.AddEntriesFrom(ref input, _repeated_screens_codec);
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class CombinedArrangement : pb::IMessage<CombinedArrangement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CombinedArrangement> _parser = new pb::MessageParser<CombinedArrangement>(() => new CombinedArrangement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CombinedArrangement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.ProPresenterScreen.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CombinedArrangement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CombinedArrangement(CombinedArrangement other) : this() {
          screens_ = other.screens_.Clone();
          rows_ = other.rows_;
          columns_ = other.columns_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CombinedArrangement Clone() {
          return new CombinedArrangement(this);
        }

        /// <summary>Field number for the "screens" field.</summary>
        public const int ScreensFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Rv.Data.Screen> _repeated_screens_codec
            = pb::FieldCodec.ForMessage(10, global::Rv.Data.Screen.Parser);
        private readonly pbc::RepeatedField<global::Rv.Data.Screen> screens_ = new pbc::RepeatedField<global::Rv.Data.Screen>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Rv.Data.Screen> Screens {
          get { return screens_; }
        }

        /// <summary>Field number for the "rows" field.</summary>
        public const int RowsFieldNumber = 2;
        private uint rows_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Rows {
          get { return rows_; }
          set {
            rows_ = value;
          }
        }

        /// <summary>Field number for the "columns" field.</summary>
        public const int ColumnsFieldNumber = 3;
        private uint columns_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Columns {
          get { return columns_; }
          set {
            columns_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CombinedArrangement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CombinedArrangement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!screens_.Equals(other.screens_)) return false;
          if (Rows != other.Rows) return false;
          if (Columns != other.Columns) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= screens_.GetHashCode();
          if (Rows != 0) hash ^= Rows.GetHashCode();
          if (Columns != 0) hash ^= Columns.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          screens_.WriteTo(output, _repeated_screens_codec);
          if (Rows != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Rows);
          }
          if (Columns != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Columns);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          screens_.WriteTo(ref output, _repeated_screens_codec);
          if (Rows != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Rows);
          }
          if (Columns != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Columns);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += screens_.CalculateSize(_repeated_screens_codec);
          if (Rows != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rows);
          }
          if (Columns != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Columns);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CombinedArrangement other) {
          if (other == null) {
            return;
          }
          screens_.Add(other.screens_);
          if (other.Rows != 0) {
            Rows = other.Rows;
          }
          if (other.Columns != 0) {
            Columns = other.Columns;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                screens_.AddEntriesFrom(input, _repeated_screens_codec);
                break;
              }
              case 16: {
                Rows = input.ReadUInt32();
                break;
              }
              case 24: {
                Columns = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                screens_.AddEntriesFrom(ref input, _repeated_screens_codec);
                break;
              }
              case 16: {
                Rows = input.ReadUInt32();
                break;
              }
              case 24: {
                Columns = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class EdgeBlendArrangement : pb::IMessage<EdgeBlendArrangement>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EdgeBlendArrangement> _parser = new pb::MessageParser<EdgeBlendArrangement>(() => new EdgeBlendArrangement());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EdgeBlendArrangement> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.ProPresenterScreen.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EdgeBlendArrangement() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EdgeBlendArrangement(EdgeBlendArrangement other) : this() {
          screenCount_ = other.screenCount_;
          screens_ = other.screens_.Clone();
          edgeBlends_ = other.edgeBlends_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EdgeBlendArrangement Clone() {
          return new EdgeBlendArrangement(this);
        }

        /// <summary>Field number for the "screen_count" field.</summary>
        public const int ScreenCountFieldNumber = 1;
        private uint screenCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ScreenCount {
          get { return screenCount_; }
          set {
            screenCount_ = value;
          }
        }

        /// <summary>Field number for the "screens" field.</summary>
        public const int ScreensFieldNumber = 2;
        private static readonly pb::FieldCodec<global::Rv.Data.Screen> _repeated_screens_codec
            = pb::FieldCodec.ForMessage(18, global::Rv.Data.Screen.Parser);
        private readonly pbc::RepeatedField<global::Rv.Data.Screen> screens_ = new pbc::RepeatedField<global::Rv.Data.Screen>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Rv.Data.Screen> Screens {
          get { return screens_; }
        }

        /// <summary>Field number for the "edge_blends" field.</summary>
        public const int EdgeBlendsFieldNumber = 3;
        private static readonly pb::FieldCodec<global::Rv.Data.EdgeBlend> _repeated_edgeBlends_codec
            = pb::FieldCodec.ForMessage(26, global::Rv.Data.EdgeBlend.Parser);
        private readonly pbc::RepeatedField<global::Rv.Data.EdgeBlend> edgeBlends_ = new pbc::RepeatedField<global::Rv.Data.EdgeBlend>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Rv.Data.EdgeBlend> EdgeBlends {
          get { return edgeBlends_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EdgeBlendArrangement);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EdgeBlendArrangement other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ScreenCount != other.ScreenCount) return false;
          if(!screens_.Equals(other.screens_)) return false;
          if(!edgeBlends_.Equals(other.edgeBlends_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ScreenCount != 0) hash ^= ScreenCount.GetHashCode();
          hash ^= screens_.GetHashCode();
          hash ^= edgeBlends_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ScreenCount != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(ScreenCount);
          }
          screens_.WriteTo(output, _repeated_screens_codec);
          edgeBlends_.WriteTo(output, _repeated_edgeBlends_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ScreenCount != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(ScreenCount);
          }
          screens_.WriteTo(ref output, _repeated_screens_codec);
          edgeBlends_.WriteTo(ref output, _repeated_edgeBlends_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ScreenCount != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScreenCount);
          }
          size += screens_.CalculateSize(_repeated_screens_codec);
          size += edgeBlends_.CalculateSize(_repeated_edgeBlends_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EdgeBlendArrangement other) {
          if (other == null) {
            return;
          }
          if (other.ScreenCount != 0) {
            ScreenCount = other.ScreenCount;
          }
          screens_.Add(other.screens_);
          edgeBlends_.Add(other.edgeBlends_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ScreenCount = input.ReadUInt32();
                break;
              }
              case 18: {
                screens_.AddEntriesFrom(input, _repeated_screens_codec);
                break;
              }
              case 26: {
                edgeBlends_.AddEntriesFrom(input, _repeated_edgeBlends_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ScreenCount = input.ReadUInt32();
                break;
              }
              case 18: {
                screens_.AddEntriesFrom(ref input, _repeated_screens_codec);
                break;
              }
              case 26: {
                edgeBlends_.AddEntriesFrom(ref input, _repeated_edgeBlends_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
