// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: workspace.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rv.Data {

  /// <summary>Holder for reflection information generated from workspace.proto</summary>
  public static partial class WorkspaceReflection {

    #region Descriptor
    /// <summary>File descriptor for workspace.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkspaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg93b3Jrc3BhY2UucHJvdG8SB3J2LmRhdGEaDWVmZmVjdHMucHJvdG8aC21h",
            "c2tzLnByb3RvGg1zY3JlZW5zLnByb3RvGgxsYXllcnMucHJvdG8aDXRhcmdl",
            "dHMucHJvdG8aDnBsYXlsaXN0LnByb3RvGgxob3RLZXkucHJvdG8aEGJhc2lj",
            "VHlwZXMucHJvdG8aDmNhbGVuZGFyLnByb3RvGhRhbGlnbm1lbnRHdWlkZS5w",
            "cm90bxoXbGl2ZVZpZGVvUGxheWxpc3QucHJvdG8aEmdyYXBoaWNzRGF0YS5w",
            "cm90byK2CQoJV29ya3NwYWNlEhsKBHV1aWQYASABKAsyDS5ydi5kYXRhLlVV",
            "SUQSDQoFbXV0ZWQYAiABKAgSDgoGaGlkZGVuGAMgASgIEj4KEWVkaXRvcl9i",
            "YWNrZ3JvdW5kGAQgASgLMiMucnYuZGF0YS5Xb3Jrc3BhY2UuRWRpdG9yQmFj",
            "a2dyb3VuZBIpChJlZmZlY3RfcHJlc2V0X3V1aWQYBSABKAsyDS5ydi5kYXRh",
            "LlVVSUQSHQoVZWZmZWN0X2J1aWxkX2R1cmF0aW9uGAYgASgBEicKCnRyYW5z",
            "aXRpb24YByABKAsyEy5ydi5kYXRhLlRyYW5zaXRpb24SJwoQYWN0aXZlX21h",
            "c2tfdXVpZBgIIAEoCzINLnJ2LmRhdGEuVVVJRBIjCghwbGF5bGlzdBgJIAEo",
            "CzIRLnJ2LmRhdGEuUGxheWxpc3QSNAoMdW5pdF9zY2FsaW5nGAogASgLMh4u",
            "cnYuZGF0YS5Xb3Jrc3BhY2UuVW5pdFNjYWxpbmcSIAoHZWZmZWN0cxgQIAMo",
            "CzIPLnJ2LmRhdGEuRWZmZWN0EhwKBW1hc2tzGBEgAygLMg0ucnYuZGF0YS5N",
            "YXNrEiAKB3NjcmVlbnMYEiADKAsyDy5ydi5kYXRhLlNjcmVlbhInCgtlZGdl",
            "X2JsZW5kcxgTIAMoCzISLnJ2LmRhdGEuRWRnZUJsZW5kEh4KBmxheWVycxgU",
            "IAMoCzIOLnJ2LmRhdGEuTGF5ZXISJwoLdGFyZ2V0X3NldHMYFSADKAsyEi5y",
            "di5kYXRhLlRhcmdldFNldBIhCghob3Rfa2V5cxgWIAMoCzIPLnJ2LmRhdGEu",
            "SG90S2V5EiMKCGNhbGVuZGFyGBcgASgLMhEucnYuZGF0YS5DYWxlbmRhchIx",
            "ChBhbGlnbm1lbnRfZ3VpZGVzGBggAygLMhcucnYuZGF0YS5BbGlnbm1lbnRH",
            "dWlkZRI3ChNsaXZlX3ZpZGVvX3BsYXlsaXN0GBkgASgLMhoucnYuZGF0YS5M",
            "aXZlVmlkZW9QbGF5bGlzdBI2ChZvdXRwdXRfcHJldmlld19kaXNwbGF5GBog",
            "ASgLMhYucnYuZGF0YS5PdXRwdXREaXNwbGF5GnYKEEVkaXRvckJhY2tncm91",
            "bmQSDwoHZW5hYmxlZBgBIAEoCBIlCgVmcmFtZRgCIAEoCzIWLnJ2LmRhdGEu",
            "R3JhcGhpY3MuUmVjdBIZCgN1cmwYAyABKAsyDC5ydi5kYXRhLlVSTBIPCgdv",
            "cGFjaXR5GAQgASgBGv0BCgtVbml0U2NhbGluZxIOCgZsZW5ndGgYASABKAES",
            "NQoEdW5pdBgCIAEoDjInLnJ2LmRhdGEuV29ya3NwYWNlLlVuaXRTY2FsaW5n",
            "LlVuaXRUeXBlEg4KBnBvaW50cxgDIAEoASKWAQoIVW5pdFR5cGUSFAoQVU5J",
            "VF9UWVBFX1BPSU5UUxAAEhkKFVVOSVRfVFlQRV9NSUxMSU1FVEVSUxABEhkK",
            "FVVOSVRfVFlQRV9DRU5USU1FVEVSUxACEhQKEFVOSVRfVFlQRV9NRVRFUlMQ",
            "AxIUChBVTklUX1RZUEVfSU5DSEVTEAQSEgoOVU5JVF9UWVBFX0ZFRVQQBWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rv.Data.EffectsReflection.Descriptor, global::Rv.Data.MasksReflection.Descriptor, global::Rv.Data.ScreensReflection.Descriptor, global::Rv.Data.LayersReflection.Descriptor, global::Rv.Data.TargetsReflection.Descriptor, global::Rv.Data.PlaylistReflection.Descriptor, global::Rv.Data.HotKeyReflection.Descriptor, global::Rv.Data.BasicTypesReflection.Descriptor, global::Rv.Data.CalendarReflection.Descriptor, global::Rv.Data.AlignmentGuideReflection.Descriptor, global::Rv.Data.LiveVideoPlaylistReflection.Descriptor, global::Rv.Data.GraphicsDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.Workspace), global::Rv.Data.Workspace.Parser, new[]{ "Uuid", "Muted", "Hidden", "EditorBackground", "EffectPresetUuid", "EffectBuildDuration", "Transition", "ActiveMaskUuid", "Playlist", "UnitScaling", "Effects", "Masks", "Screens", "EdgeBlends", "Layers", "TargetSets", "HotKeys", "Calendar", "AlignmentGuides", "LiveVideoPlaylist", "OutputPreviewDisplay" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.Workspace.Types.EditorBackground), global::Rv.Data.Workspace.Types.EditorBackground.Parser, new[]{ "Enabled", "Frame", "Url", "Opacity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rv.Data.Workspace.Types.UnitScaling), global::Rv.Data.Workspace.Types.UnitScaling.Parser, new[]{ "Length", "Unit", "Points" }, null, new[]{ typeof(global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Workspace : pb::IMessage<Workspace>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Workspace> _parser = new pb::MessageParser<Workspace>(() => new Workspace());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Workspace> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rv.Data.WorkspaceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Workspace() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Workspace(Workspace other) : this() {
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      muted_ = other.muted_;
      hidden_ = other.hidden_;
      editorBackground_ = other.editorBackground_ != null ? other.editorBackground_.Clone() : null;
      effectPresetUuid_ = other.effectPresetUuid_ != null ? other.effectPresetUuid_.Clone() : null;
      effectBuildDuration_ = other.effectBuildDuration_;
      transition_ = other.transition_ != null ? other.transition_.Clone() : null;
      activeMaskUuid_ = other.activeMaskUuid_ != null ? other.activeMaskUuid_.Clone() : null;
      playlist_ = other.playlist_ != null ? other.playlist_.Clone() : null;
      unitScaling_ = other.unitScaling_ != null ? other.unitScaling_.Clone() : null;
      effects_ = other.effects_.Clone();
      masks_ = other.masks_.Clone();
      screens_ = other.screens_.Clone();
      edgeBlends_ = other.edgeBlends_.Clone();
      layers_ = other.layers_.Clone();
      targetSets_ = other.targetSets_.Clone();
      hotKeys_ = other.hotKeys_.Clone();
      calendar_ = other.calendar_ != null ? other.calendar_.Clone() : null;
      alignmentGuides_ = other.alignmentGuides_.Clone();
      liveVideoPlaylist_ = other.liveVideoPlaylist_ != null ? other.liveVideoPlaylist_.Clone() : null;
      outputPreviewDisplay_ = other.outputPreviewDisplay_ != null ? other.outputPreviewDisplay_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Workspace Clone() {
      return new Workspace(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private global::Rv.Data.UUID uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    /// <summary>Field number for the "muted" field.</summary>
    public const int MutedFieldNumber = 2;
    private bool muted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Muted {
      get { return muted_; }
      set {
        muted_ = value;
      }
    }

    /// <summary>Field number for the "hidden" field.</summary>
    public const int HiddenFieldNumber = 3;
    private bool hidden_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Hidden {
      get { return hidden_; }
      set {
        hidden_ = value;
      }
    }

    /// <summary>Field number for the "editor_background" field.</summary>
    public const int EditorBackgroundFieldNumber = 4;
    private global::Rv.Data.Workspace.Types.EditorBackground editorBackground_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Workspace.Types.EditorBackground EditorBackground {
      get { return editorBackground_; }
      set {
        editorBackground_ = value;
      }
    }

    /// <summary>Field number for the "effect_preset_uuid" field.</summary>
    public const int EffectPresetUuidFieldNumber = 5;
    private global::Rv.Data.UUID effectPresetUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID EffectPresetUuid {
      get { return effectPresetUuid_; }
      set {
        effectPresetUuid_ = value;
      }
    }

    /// <summary>Field number for the "effect_build_duration" field.</summary>
    public const int EffectBuildDurationFieldNumber = 6;
    private double effectBuildDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double EffectBuildDuration {
      get { return effectBuildDuration_; }
      set {
        effectBuildDuration_ = value;
      }
    }

    /// <summary>Field number for the "transition" field.</summary>
    public const int TransitionFieldNumber = 7;
    private global::Rv.Data.Transition transition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Transition Transition {
      get { return transition_; }
      set {
        transition_ = value;
      }
    }

    /// <summary>Field number for the "active_mask_uuid" field.</summary>
    public const int ActiveMaskUuidFieldNumber = 8;
    private global::Rv.Data.UUID activeMaskUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.UUID ActiveMaskUuid {
      get { return activeMaskUuid_; }
      set {
        activeMaskUuid_ = value;
      }
    }

    /// <summary>Field number for the "playlist" field.</summary>
    public const int PlaylistFieldNumber = 9;
    private global::Rv.Data.Playlist playlist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Playlist Playlist {
      get { return playlist_; }
      set {
        playlist_ = value;
      }
    }

    /// <summary>Field number for the "unit_scaling" field.</summary>
    public const int UnitScalingFieldNumber = 10;
    private global::Rv.Data.Workspace.Types.UnitScaling unitScaling_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Workspace.Types.UnitScaling UnitScaling {
      get { return unitScaling_; }
      set {
        unitScaling_ = value;
      }
    }

    /// <summary>Field number for the "effects" field.</summary>
    public const int EffectsFieldNumber = 16;
    private static readonly pb::FieldCodec<global::Rv.Data.Effect> _repeated_effects_codec
        = pb::FieldCodec.ForMessage(130, global::Rv.Data.Effect.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Effect> effects_ = new pbc::RepeatedField<global::Rv.Data.Effect>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Effect> Effects {
      get { return effects_; }
    }

    /// <summary>Field number for the "masks" field.</summary>
    public const int MasksFieldNumber = 17;
    private static readonly pb::FieldCodec<global::Rv.Data.Mask> _repeated_masks_codec
        = pb::FieldCodec.ForMessage(138, global::Rv.Data.Mask.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Mask> masks_ = new pbc::RepeatedField<global::Rv.Data.Mask>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Mask> Masks {
      get { return masks_; }
    }

    /// <summary>Field number for the "screens" field.</summary>
    public const int ScreensFieldNumber = 18;
    private static readonly pb::FieldCodec<global::Rv.Data.Screen> _repeated_screens_codec
        = pb::FieldCodec.ForMessage(146, global::Rv.Data.Screen.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Screen> screens_ = new pbc::RepeatedField<global::Rv.Data.Screen>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Screen> Screens {
      get { return screens_; }
    }

    /// <summary>Field number for the "edge_blends" field.</summary>
    public const int EdgeBlendsFieldNumber = 19;
    private static readonly pb::FieldCodec<global::Rv.Data.EdgeBlend> _repeated_edgeBlends_codec
        = pb::FieldCodec.ForMessage(154, global::Rv.Data.EdgeBlend.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.EdgeBlend> edgeBlends_ = new pbc::RepeatedField<global::Rv.Data.EdgeBlend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.EdgeBlend> EdgeBlends {
      get { return edgeBlends_; }
    }

    /// <summary>Field number for the "layers" field.</summary>
    public const int LayersFieldNumber = 20;
    private static readonly pb::FieldCodec<global::Rv.Data.Layer> _repeated_layers_codec
        = pb::FieldCodec.ForMessage(162, global::Rv.Data.Layer.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.Layer> layers_ = new pbc::RepeatedField<global::Rv.Data.Layer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.Layer> Layers {
      get { return layers_; }
    }

    /// <summary>Field number for the "target_sets" field.</summary>
    public const int TargetSetsFieldNumber = 21;
    private static readonly pb::FieldCodec<global::Rv.Data.TargetSet> _repeated_targetSets_codec
        = pb::FieldCodec.ForMessage(170, global::Rv.Data.TargetSet.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.TargetSet> targetSets_ = new pbc::RepeatedField<global::Rv.Data.TargetSet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.TargetSet> TargetSets {
      get { return targetSets_; }
    }

    /// <summary>Field number for the "hot_keys" field.</summary>
    public const int HotKeysFieldNumber = 22;
    private static readonly pb::FieldCodec<global::Rv.Data.HotKey> _repeated_hotKeys_codec
        = pb::FieldCodec.ForMessage(178, global::Rv.Data.HotKey.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.HotKey> hotKeys_ = new pbc::RepeatedField<global::Rv.Data.HotKey>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.HotKey> HotKeys {
      get { return hotKeys_; }
    }

    /// <summary>Field number for the "calendar" field.</summary>
    public const int CalendarFieldNumber = 23;
    private global::Rv.Data.Calendar calendar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.Calendar Calendar {
      get { return calendar_; }
      set {
        calendar_ = value;
      }
    }

    /// <summary>Field number for the "alignment_guides" field.</summary>
    public const int AlignmentGuidesFieldNumber = 24;
    private static readonly pb::FieldCodec<global::Rv.Data.AlignmentGuide> _repeated_alignmentGuides_codec
        = pb::FieldCodec.ForMessage(194, global::Rv.Data.AlignmentGuide.Parser);
    private readonly pbc::RepeatedField<global::Rv.Data.AlignmentGuide> alignmentGuides_ = new pbc::RepeatedField<global::Rv.Data.AlignmentGuide>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Rv.Data.AlignmentGuide> AlignmentGuides {
      get { return alignmentGuides_; }
    }

    /// <summary>Field number for the "live_video_playlist" field.</summary>
    public const int LiveVideoPlaylistFieldNumber = 25;
    private global::Rv.Data.LiveVideoPlaylist liveVideoPlaylist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.LiveVideoPlaylist LiveVideoPlaylist {
      get { return liveVideoPlaylist_; }
      set {
        liveVideoPlaylist_ = value;
      }
    }

    /// <summary>Field number for the "output_preview_display" field.</summary>
    public const int OutputPreviewDisplayFieldNumber = 26;
    private global::Rv.Data.OutputDisplay outputPreviewDisplay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Rv.Data.OutputDisplay OutputPreviewDisplay {
      get { return outputPreviewDisplay_; }
      set {
        outputPreviewDisplay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Workspace);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Workspace other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Uuid, other.Uuid)) return false;
      if (Muted != other.Muted) return false;
      if (Hidden != other.Hidden) return false;
      if (!object.Equals(EditorBackground, other.EditorBackground)) return false;
      if (!object.Equals(EffectPresetUuid, other.EffectPresetUuid)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EffectBuildDuration, other.EffectBuildDuration)) return false;
      if (!object.Equals(Transition, other.Transition)) return false;
      if (!object.Equals(ActiveMaskUuid, other.ActiveMaskUuid)) return false;
      if (!object.Equals(Playlist, other.Playlist)) return false;
      if (!object.Equals(UnitScaling, other.UnitScaling)) return false;
      if(!effects_.Equals(other.effects_)) return false;
      if(!masks_.Equals(other.masks_)) return false;
      if(!screens_.Equals(other.screens_)) return false;
      if(!edgeBlends_.Equals(other.edgeBlends_)) return false;
      if(!layers_.Equals(other.layers_)) return false;
      if(!targetSets_.Equals(other.targetSets_)) return false;
      if(!hotKeys_.Equals(other.hotKeys_)) return false;
      if (!object.Equals(Calendar, other.Calendar)) return false;
      if(!alignmentGuides_.Equals(other.alignmentGuides_)) return false;
      if (!object.Equals(LiveVideoPlaylist, other.LiveVideoPlaylist)) return false;
      if (!object.Equals(OutputPreviewDisplay, other.OutputPreviewDisplay)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (Muted != false) hash ^= Muted.GetHashCode();
      if (Hidden != false) hash ^= Hidden.GetHashCode();
      if (editorBackground_ != null) hash ^= EditorBackground.GetHashCode();
      if (effectPresetUuid_ != null) hash ^= EffectPresetUuid.GetHashCode();
      if (EffectBuildDuration != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EffectBuildDuration);
      if (transition_ != null) hash ^= Transition.GetHashCode();
      if (activeMaskUuid_ != null) hash ^= ActiveMaskUuid.GetHashCode();
      if (playlist_ != null) hash ^= Playlist.GetHashCode();
      if (unitScaling_ != null) hash ^= UnitScaling.GetHashCode();
      hash ^= effects_.GetHashCode();
      hash ^= masks_.GetHashCode();
      hash ^= screens_.GetHashCode();
      hash ^= edgeBlends_.GetHashCode();
      hash ^= layers_.GetHashCode();
      hash ^= targetSets_.GetHashCode();
      hash ^= hotKeys_.GetHashCode();
      if (calendar_ != null) hash ^= Calendar.GetHashCode();
      hash ^= alignmentGuides_.GetHashCode();
      if (liveVideoPlaylist_ != null) hash ^= LiveVideoPlaylist.GetHashCode();
      if (outputPreviewDisplay_ != null) hash ^= OutputPreviewDisplay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (uuid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Uuid);
      }
      if (Muted != false) {
        output.WriteRawTag(16);
        output.WriteBool(Muted);
      }
      if (Hidden != false) {
        output.WriteRawTag(24);
        output.WriteBool(Hidden);
      }
      if (editorBackground_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EditorBackground);
      }
      if (effectPresetUuid_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EffectPresetUuid);
      }
      if (EffectBuildDuration != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(EffectBuildDuration);
      }
      if (transition_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Transition);
      }
      if (activeMaskUuid_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ActiveMaskUuid);
      }
      if (playlist_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Playlist);
      }
      if (unitScaling_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(UnitScaling);
      }
      effects_.WriteTo(output, _repeated_effects_codec);
      masks_.WriteTo(output, _repeated_masks_codec);
      screens_.WriteTo(output, _repeated_screens_codec);
      edgeBlends_.WriteTo(output, _repeated_edgeBlends_codec);
      layers_.WriteTo(output, _repeated_layers_codec);
      targetSets_.WriteTo(output, _repeated_targetSets_codec);
      hotKeys_.WriteTo(output, _repeated_hotKeys_codec);
      if (calendar_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(Calendar);
      }
      alignmentGuides_.WriteTo(output, _repeated_alignmentGuides_codec);
      if (liveVideoPlaylist_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(LiveVideoPlaylist);
      }
      if (outputPreviewDisplay_ != null) {
        output.WriteRawTag(210, 1);
        output.WriteMessage(OutputPreviewDisplay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (uuid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Uuid);
      }
      if (Muted != false) {
        output.WriteRawTag(16);
        output.WriteBool(Muted);
      }
      if (Hidden != false) {
        output.WriteRawTag(24);
        output.WriteBool(Hidden);
      }
      if (editorBackground_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EditorBackground);
      }
      if (effectPresetUuid_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EffectPresetUuid);
      }
      if (EffectBuildDuration != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(EffectBuildDuration);
      }
      if (transition_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Transition);
      }
      if (activeMaskUuid_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ActiveMaskUuid);
      }
      if (playlist_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Playlist);
      }
      if (unitScaling_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(UnitScaling);
      }
      effects_.WriteTo(ref output, _repeated_effects_codec);
      masks_.WriteTo(ref output, _repeated_masks_codec);
      screens_.WriteTo(ref output, _repeated_screens_codec);
      edgeBlends_.WriteTo(ref output, _repeated_edgeBlends_codec);
      layers_.WriteTo(ref output, _repeated_layers_codec);
      targetSets_.WriteTo(ref output, _repeated_targetSets_codec);
      hotKeys_.WriteTo(ref output, _repeated_hotKeys_codec);
      if (calendar_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(Calendar);
      }
      alignmentGuides_.WriteTo(ref output, _repeated_alignmentGuides_codec);
      if (liveVideoPlaylist_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(LiveVideoPlaylist);
      }
      if (outputPreviewDisplay_ != null) {
        output.WriteRawTag(210, 1);
        output.WriteMessage(OutputPreviewDisplay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (Muted != false) {
        size += 1 + 1;
      }
      if (Hidden != false) {
        size += 1 + 1;
      }
      if (editorBackground_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EditorBackground);
      }
      if (effectPresetUuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EffectPresetUuid);
      }
      if (EffectBuildDuration != 0D) {
        size += 1 + 8;
      }
      if (transition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transition);
      }
      if (activeMaskUuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActiveMaskUuid);
      }
      if (playlist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Playlist);
      }
      if (unitScaling_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnitScaling);
      }
      size += effects_.CalculateSize(_repeated_effects_codec);
      size += masks_.CalculateSize(_repeated_masks_codec);
      size += screens_.CalculateSize(_repeated_screens_codec);
      size += edgeBlends_.CalculateSize(_repeated_edgeBlends_codec);
      size += layers_.CalculateSize(_repeated_layers_codec);
      size += targetSets_.CalculateSize(_repeated_targetSets_codec);
      size += hotKeys_.CalculateSize(_repeated_hotKeys_codec);
      if (calendar_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Calendar);
      }
      size += alignmentGuides_.CalculateSize(_repeated_alignmentGuides_codec);
      if (liveVideoPlaylist_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LiveVideoPlaylist);
      }
      if (outputPreviewDisplay_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OutputPreviewDisplay);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Workspace other) {
      if (other == null) {
        return;
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::Rv.Data.UUID();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      if (other.Muted != false) {
        Muted = other.Muted;
      }
      if (other.Hidden != false) {
        Hidden = other.Hidden;
      }
      if (other.editorBackground_ != null) {
        if (editorBackground_ == null) {
          EditorBackground = new global::Rv.Data.Workspace.Types.EditorBackground();
        }
        EditorBackground.MergeFrom(other.EditorBackground);
      }
      if (other.effectPresetUuid_ != null) {
        if (effectPresetUuid_ == null) {
          EffectPresetUuid = new global::Rv.Data.UUID();
        }
        EffectPresetUuid.MergeFrom(other.EffectPresetUuid);
      }
      if (other.EffectBuildDuration != 0D) {
        EffectBuildDuration = other.EffectBuildDuration;
      }
      if (other.transition_ != null) {
        if (transition_ == null) {
          Transition = new global::Rv.Data.Transition();
        }
        Transition.MergeFrom(other.Transition);
      }
      if (other.activeMaskUuid_ != null) {
        if (activeMaskUuid_ == null) {
          ActiveMaskUuid = new global::Rv.Data.UUID();
        }
        ActiveMaskUuid.MergeFrom(other.ActiveMaskUuid);
      }
      if (other.playlist_ != null) {
        if (playlist_ == null) {
          Playlist = new global::Rv.Data.Playlist();
        }
        Playlist.MergeFrom(other.Playlist);
      }
      if (other.unitScaling_ != null) {
        if (unitScaling_ == null) {
          UnitScaling = new global::Rv.Data.Workspace.Types.UnitScaling();
        }
        UnitScaling.MergeFrom(other.UnitScaling);
      }
      effects_.Add(other.effects_);
      masks_.Add(other.masks_);
      screens_.Add(other.screens_);
      edgeBlends_.Add(other.edgeBlends_);
      layers_.Add(other.layers_);
      targetSets_.Add(other.targetSets_);
      hotKeys_.Add(other.hotKeys_);
      if (other.calendar_ != null) {
        if (calendar_ == null) {
          Calendar = new global::Rv.Data.Calendar();
        }
        Calendar.MergeFrom(other.Calendar);
      }
      alignmentGuides_.Add(other.alignmentGuides_);
      if (other.liveVideoPlaylist_ != null) {
        if (liveVideoPlaylist_ == null) {
          LiveVideoPlaylist = new global::Rv.Data.LiveVideoPlaylist();
        }
        LiveVideoPlaylist.MergeFrom(other.LiveVideoPlaylist);
      }
      if (other.outputPreviewDisplay_ != null) {
        if (outputPreviewDisplay_ == null) {
          OutputPreviewDisplay = new global::Rv.Data.OutputDisplay();
        }
        OutputPreviewDisplay.MergeFrom(other.OutputPreviewDisplay);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 16: {
            Muted = input.ReadBool();
            break;
          }
          case 24: {
            Hidden = input.ReadBool();
            break;
          }
          case 34: {
            if (editorBackground_ == null) {
              EditorBackground = new global::Rv.Data.Workspace.Types.EditorBackground();
            }
            input.ReadMessage(EditorBackground);
            break;
          }
          case 42: {
            if (effectPresetUuid_ == null) {
              EffectPresetUuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(EffectPresetUuid);
            break;
          }
          case 49: {
            EffectBuildDuration = input.ReadDouble();
            break;
          }
          case 58: {
            if (transition_ == null) {
              Transition = new global::Rv.Data.Transition();
            }
            input.ReadMessage(Transition);
            break;
          }
          case 66: {
            if (activeMaskUuid_ == null) {
              ActiveMaskUuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(ActiveMaskUuid);
            break;
          }
          case 74: {
            if (playlist_ == null) {
              Playlist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(Playlist);
            break;
          }
          case 82: {
            if (unitScaling_ == null) {
              UnitScaling = new global::Rv.Data.Workspace.Types.UnitScaling();
            }
            input.ReadMessage(UnitScaling);
            break;
          }
          case 130: {
            effects_.AddEntriesFrom(input, _repeated_effects_codec);
            break;
          }
          case 138: {
            masks_.AddEntriesFrom(input, _repeated_masks_codec);
            break;
          }
          case 146: {
            screens_.AddEntriesFrom(input, _repeated_screens_codec);
            break;
          }
          case 154: {
            edgeBlends_.AddEntriesFrom(input, _repeated_edgeBlends_codec);
            break;
          }
          case 162: {
            layers_.AddEntriesFrom(input, _repeated_layers_codec);
            break;
          }
          case 170: {
            targetSets_.AddEntriesFrom(input, _repeated_targetSets_codec);
            break;
          }
          case 178: {
            hotKeys_.AddEntriesFrom(input, _repeated_hotKeys_codec);
            break;
          }
          case 186: {
            if (calendar_ == null) {
              Calendar = new global::Rv.Data.Calendar();
            }
            input.ReadMessage(Calendar);
            break;
          }
          case 194: {
            alignmentGuides_.AddEntriesFrom(input, _repeated_alignmentGuides_codec);
            break;
          }
          case 202: {
            if (liveVideoPlaylist_ == null) {
              LiveVideoPlaylist = new global::Rv.Data.LiveVideoPlaylist();
            }
            input.ReadMessage(LiveVideoPlaylist);
            break;
          }
          case 210: {
            if (outputPreviewDisplay_ == null) {
              OutputPreviewDisplay = new global::Rv.Data.OutputDisplay();
            }
            input.ReadMessage(OutputPreviewDisplay);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (uuid_ == null) {
              Uuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(Uuid);
            break;
          }
          case 16: {
            Muted = input.ReadBool();
            break;
          }
          case 24: {
            Hidden = input.ReadBool();
            break;
          }
          case 34: {
            if (editorBackground_ == null) {
              EditorBackground = new global::Rv.Data.Workspace.Types.EditorBackground();
            }
            input.ReadMessage(EditorBackground);
            break;
          }
          case 42: {
            if (effectPresetUuid_ == null) {
              EffectPresetUuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(EffectPresetUuid);
            break;
          }
          case 49: {
            EffectBuildDuration = input.ReadDouble();
            break;
          }
          case 58: {
            if (transition_ == null) {
              Transition = new global::Rv.Data.Transition();
            }
            input.ReadMessage(Transition);
            break;
          }
          case 66: {
            if (activeMaskUuid_ == null) {
              ActiveMaskUuid = new global::Rv.Data.UUID();
            }
            input.ReadMessage(ActiveMaskUuid);
            break;
          }
          case 74: {
            if (playlist_ == null) {
              Playlist = new global::Rv.Data.Playlist();
            }
            input.ReadMessage(Playlist);
            break;
          }
          case 82: {
            if (unitScaling_ == null) {
              UnitScaling = new global::Rv.Data.Workspace.Types.UnitScaling();
            }
            input.ReadMessage(UnitScaling);
            break;
          }
          case 130: {
            effects_.AddEntriesFrom(ref input, _repeated_effects_codec);
            break;
          }
          case 138: {
            masks_.AddEntriesFrom(ref input, _repeated_masks_codec);
            break;
          }
          case 146: {
            screens_.AddEntriesFrom(ref input, _repeated_screens_codec);
            break;
          }
          case 154: {
            edgeBlends_.AddEntriesFrom(ref input, _repeated_edgeBlends_codec);
            break;
          }
          case 162: {
            layers_.AddEntriesFrom(ref input, _repeated_layers_codec);
            break;
          }
          case 170: {
            targetSets_.AddEntriesFrom(ref input, _repeated_targetSets_codec);
            break;
          }
          case 178: {
            hotKeys_.AddEntriesFrom(ref input, _repeated_hotKeys_codec);
            break;
          }
          case 186: {
            if (calendar_ == null) {
              Calendar = new global::Rv.Data.Calendar();
            }
            input.ReadMessage(Calendar);
            break;
          }
          case 194: {
            alignmentGuides_.AddEntriesFrom(ref input, _repeated_alignmentGuides_codec);
            break;
          }
          case 202: {
            if (liveVideoPlaylist_ == null) {
              LiveVideoPlaylist = new global::Rv.Data.LiveVideoPlaylist();
            }
            input.ReadMessage(LiveVideoPlaylist);
            break;
          }
          case 210: {
            if (outputPreviewDisplay_ == null) {
              OutputPreviewDisplay = new global::Rv.Data.OutputDisplay();
            }
            input.ReadMessage(OutputPreviewDisplay);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Workspace message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class EditorBackground : pb::IMessage<EditorBackground>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EditorBackground> _parser = new pb::MessageParser<EditorBackground>(() => new EditorBackground());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EditorBackground> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.Workspace.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EditorBackground() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EditorBackground(EditorBackground other) : this() {
          enabled_ = other.enabled_;
          frame_ = other.frame_ != null ? other.frame_.Clone() : null;
          url_ = other.url_ != null ? other.url_.Clone() : null;
          opacity_ = other.opacity_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EditorBackground Clone() {
          return new EditorBackground(this);
        }

        /// <summary>Field number for the "enabled" field.</summary>
        public const int EnabledFieldNumber = 1;
        private bool enabled_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Enabled {
          get { return enabled_; }
          set {
            enabled_ = value;
          }
        }

        /// <summary>Field number for the "frame" field.</summary>
        public const int FrameFieldNumber = 2;
        private global::Rv.Data.Graphics.Types.Rect frame_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.Graphics.Types.Rect Frame {
          get { return frame_; }
          set {
            frame_ = value;
          }
        }

        /// <summary>Field number for the "url" field.</summary>
        public const int UrlFieldNumber = 3;
        private global::Rv.Data.URL url_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.URL Url {
          get { return url_; }
          set {
            url_ = value;
          }
        }

        /// <summary>Field number for the "opacity" field.</summary>
        public const int OpacityFieldNumber = 4;
        private double opacity_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Opacity {
          get { return opacity_; }
          set {
            opacity_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EditorBackground);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EditorBackground other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Enabled != other.Enabled) return false;
          if (!object.Equals(Frame, other.Frame)) return false;
          if (!object.Equals(Url, other.Url)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Opacity, other.Opacity)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Enabled != false) hash ^= Enabled.GetHashCode();
          if (frame_ != null) hash ^= Frame.GetHashCode();
          if (url_ != null) hash ^= Url.GetHashCode();
          if (Opacity != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Opacity);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Enabled != false) {
            output.WriteRawTag(8);
            output.WriteBool(Enabled);
          }
          if (frame_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Frame);
          }
          if (url_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Url);
          }
          if (Opacity != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(Opacity);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Enabled != false) {
            output.WriteRawTag(8);
            output.WriteBool(Enabled);
          }
          if (frame_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Frame);
          }
          if (url_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Url);
          }
          if (Opacity != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(Opacity);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Enabled != false) {
            size += 1 + 1;
          }
          if (frame_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Frame);
          }
          if (url_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Url);
          }
          if (Opacity != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EditorBackground other) {
          if (other == null) {
            return;
          }
          if (other.Enabled != false) {
            Enabled = other.Enabled;
          }
          if (other.frame_ != null) {
            if (frame_ == null) {
              Frame = new global::Rv.Data.Graphics.Types.Rect();
            }
            Frame.MergeFrom(other.Frame);
          }
          if (other.url_ != null) {
            if (url_ == null) {
              Url = new global::Rv.Data.URL();
            }
            Url.MergeFrom(other.Url);
          }
          if (other.Opacity != 0D) {
            Opacity = other.Opacity;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Enabled = input.ReadBool();
                break;
              }
              case 18: {
                if (frame_ == null) {
                  Frame = new global::Rv.Data.Graphics.Types.Rect();
                }
                input.ReadMessage(Frame);
                break;
              }
              case 26: {
                if (url_ == null) {
                  Url = new global::Rv.Data.URL();
                }
                input.ReadMessage(Url);
                break;
              }
              case 33: {
                Opacity = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Enabled = input.ReadBool();
                break;
              }
              case 18: {
                if (frame_ == null) {
                  Frame = new global::Rv.Data.Graphics.Types.Rect();
                }
                input.ReadMessage(Frame);
                break;
              }
              case 26: {
                if (url_ == null) {
                  Url = new global::Rv.Data.URL();
                }
                input.ReadMessage(Url);
                break;
              }
              case 33: {
                Opacity = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class UnitScaling : pb::IMessage<UnitScaling>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UnitScaling> _parser = new pb::MessageParser<UnitScaling>(() => new UnitScaling());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<UnitScaling> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Rv.Data.Workspace.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnitScaling() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnitScaling(UnitScaling other) : this() {
          length_ = other.length_;
          unit_ = other.unit_;
          points_ = other.points_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnitScaling Clone() {
          return new UnitScaling(this);
        }

        /// <summary>Field number for the "length" field.</summary>
        public const int LengthFieldNumber = 1;
        private double length_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Length {
          get { return length_; }
          set {
            length_ = value;
          }
        }

        /// <summary>Field number for the "unit" field.</summary>
        public const int UnitFieldNumber = 2;
        private global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType unit_ = global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType Unit {
          get { return unit_; }
          set {
            unit_ = value;
          }
        }

        /// <summary>Field number for the "points" field.</summary>
        public const int PointsFieldNumber = 3;
        private double points_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Points {
          get { return points_; }
          set {
            points_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as UnitScaling);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(UnitScaling other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Length, other.Length)) return false;
          if (Unit != other.Unit) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Points, other.Points)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Length != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Length);
          if (Unit != global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points) hash ^= Unit.GetHashCode();
          if (Points != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Points);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Length != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(Length);
          }
          if (Unit != global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Unit);
          }
          if (Points != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(Points);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Length != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(Length);
          }
          if (Unit != global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Unit);
          }
          if (Points != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(Points);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Length != 0D) {
            size += 1 + 8;
          }
          if (Unit != global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Unit);
          }
          if (Points != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(UnitScaling other) {
          if (other == null) {
            return;
          }
          if (other.Length != 0D) {
            Length = other.Length;
          }
          if (other.Unit != global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType.Points) {
            Unit = other.Unit;
          }
          if (other.Points != 0D) {
            Points = other.Points;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                Length = input.ReadDouble();
                break;
              }
              case 16: {
                Unit = (global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType) input.ReadEnum();
                break;
              }
              case 25: {
                Points = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 9: {
                Length = input.ReadDouble();
                break;
              }
              case 16: {
                Unit = (global::Rv.Data.Workspace.Types.UnitScaling.Types.UnitType) input.ReadEnum();
                break;
              }
              case 25: {
                Points = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the UnitScaling message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum UnitType {
            [pbr::OriginalName("UNIT_TYPE_POINTS")] Points = 0,
            [pbr::OriginalName("UNIT_TYPE_MILLIMETERS")] Millimeters = 1,
            [pbr::OriginalName("UNIT_TYPE_CENTIMETERS")] Centimeters = 2,
            [pbr::OriginalName("UNIT_TYPE_METERS")] Meters = 3,
            [pbr::OriginalName("UNIT_TYPE_INCHES")] Inches = 4,
            [pbr::OriginalName("UNIT_TYPE_FEET")] Feet = 5,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
